import {formatMoney,moneyData} from '../format.js';
import {loadSeason,peekSeason,saveEconomyAction} from './store.js';
import {localDivisions,localClubById,LOCAL_TIERS} from './local-catalog.js';
import {clubIdentity} from './team-directory.js';
import {regions} from '../world.js';
import {publicBalance} from './public-credit.js';
import {standings} from './season.js';
import {unpaidTotal} from './payables.js';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>moneyData(n??0),name=id=>clubIdentity(id)?.name||id,status=c=>({normal:'正常',administration:'托管',dissolved:'已解散'})[c?.status]||'正常';
const table=(heads,rows)=>`<div class="manager-table-wrap"><table class="manager-table"><thead><tr>${heads.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map(x=>`<td>${x}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
let root,token=0,division=localDivisions[0].id,selected=null,notice='',busy=false;
export function economyContent(s){
 const e=s.economy,w=e?.world;if(!w)return '<h1>地方足球与经济</h1><p>此存档未启用省市体系。</p>';
 const d=localDivisions.find(d=>d.id===division),ids=w.members[division];if(!ids.includes(selected))selected=ids[0];
 const c=w.clubs[selected],a=c.finance,fixtures=w.fixtures.filter(m=>m.competition===division),ranks=standings(ids,fixtures,{seed:`${w.year}:${division}`}),own=s.manager?.clubId,account=own&&e.accounts[own],debt=own&&w.credit[own];
 return `<header class="football-title"><div><small>${s.date}</small><h1>地方足球与经济</h1></div><a href="#finance">俱乐部财政 ↗</a></header>
 <div class="manager-stats manager-season-stats">${[[Object.values(w.clubs).filter(c=>c.status==='active').length,'地方俱乐部'],[Object.values(w.players).filter(p=>p.status==='local').length,'地方球员'],[w.fixtureCursor,'本季已赛'],[w.events.filter(x=>x.type==='core-replacement'||x.type==='career-up'||x.type==='career-down').length,'跨体系流动']].map(([n,label])=>`<div><strong>${n.toLocaleString('zh-CN')}</strong><span>${label}</span></div>`).join('')}</div>
 <section class="manager-panel"><h2>省市联赛</h2><label>联赛<select data-economy-division>${localDivisions.map(x=>`<option value="${x.id}" ${x.id===division?'selected':''}>${esc(x.name)}</option>`).join('')}</select></label>${table(['排名','球队','场次','积分','声望','现金','贷款本金','应付款','状态'],ranks.map(r=>{const f=w.clubs[r.id].finance;return [r.rank,`<button data-economy-club="${r.id}">${esc(name(r.id))}</button>`,r.played,r.points,w.clubs[r.id].reputation==null?'—':Math.round(w.clubs[r.id].reputation).toLocaleString('zh-CN'),money(f.cash),money(w.credit[r.id]?.principal),money(unpaidTotal(f)),status(w.credit[r.id])];}))}</section>
 <section class="manager-panel"><h2>${esc(name(selected))} · ${LOCAL_TIERS[c.tier].name}</h2>${table(['项目','星元'],[['本季外部收入与拨款',money(a.season.funding)],['公共拨款',money(a.income.publicGrant)],['税前工资实付',money(a.season.wages)],['代扣个税',money(a.withholding.season.incomeTax)],['球员实得',money(a.withholding.season.net)],['转会净收入',money(a.season.transferIn-a.season.transferOut)],['运营实付',money(a.season.operating)],['利息实付',money(a.season.interest)]])}${table(['球员','位置','年龄','能力 / 200','周薪','本季分钟','进球'],c.roster.map(id=>w.players[id]).map(p=>[esc(p.name),p.position,s.year-p.birthYear,p.ability.toFixed(1),money(p.weeklyWage),p.seasonMinutes,p.seasonGoals]))}</section>
 <section class="manager-panel"><h2>赛程与结果</h2>${table(['日期','主队','比分','客队'],fixtures.filter(m=>m.home===selected||m.away===selected).map(m=>[m.date,esc(name(m.home)),m.score?.join(' : ')||'待赛',esc(name(m.away))]))}</section>
 <section class="manager-panel"><h2>公共资金与银行</h2>${table(['地区','政府余额','联盟余额','基层与青训拨款','设施支出','公共服务','托管投入','银行现金','贷款损失'],regions.map(r=>{const p=w.public[r.id],b=w.banks[r.id];return [r.name,money(publicBalance(e,r.id)),money(publicBalance(e,r.id,true)),money(p.grassroots+p.youth),money(p.facilities),money(p.services),money(p.rescue),money(b.cash),money(b.losses)];}))}</section>
 ${own?`<section class="manager-panel"><h2>${esc(name(own))} · 债务与托管</h2><p>状态：${status(debt)} · 贷款本金 ${money(debt?.principal)} · 欠息 ${money(debt?.interestArrears)} · 应付款 ${money(unpaidTotal(account))}</p><label>金额（万星元）<input data-economy-amount type="number" min="0.0001" step="0.0001" value="${Number((Math.max(1,Math.floor(account.operatingRevenueBudget/12))/10000).toFixed(4))}"></label><button data-economy-action="borrow" ${busy?'disabled':''}>申请贷款</button><button data-economy-action="repay" ${busy?'disabled':''}>偿还本金</button><button data-economy-action="administration" ${busy?'disabled':''}>申请托管</button>${debt?.status==='administration'?`<button data-economy-action="dissolve" ${busy||debt.dissolveAfterSeason?'disabled':''}>${debt.dissolveAfterSeason?'已安排季末解散':'安排季末解散'}</button>`:''}<p>年利率 6% · 授信不超过预计经营收入的 35% · 托管期间限制引援</p><p role="status">${esc(notice)}</p></section>`:''}
 <section class="manager-panel"><h2>最近经济事件</h2>${table(['日期','事件','俱乐部 / 地区','金额'],w.events.slice(-30).reverse().map(x=>[x.date,esc(({loan:'贷款',administration:'进入托管','administration-exit':'结束托管','custody-grant':'托管拨款','creditor-loss':'债权损失','public-spending':'公共支出','core-replacement':'解散与递补','career-up':'进入职业联赛','career-down':'回流地方','dissolution-pending':'计划解散'})[x.type]||x.type),esc(name(x.club||x.replacement||x.from||x.region||'')),money(x.amount??(x.grants||0)+(x.facilities||0)+(x.services||0)+(x.youth||0))]))}</section>`;
}
export const renderEconomy=()=>'<section class="football-page" id="economy-root"><p>正在读取地方赛历…</p></section>';
export function disposeEconomy(){token++;root=null;}
export async function mountEconomy(){root=document.querySelector('#economy-root');const current=++token;await loadSeason();if(current!==token)return;const draw=()=>{if(root)root.innerHTML=economyContent(peekSeason());};draw();root.addEventListener('change',ev=>{if(ev.target.hasAttribute('data-economy-division')){division=ev.target.value;selected=null;draw();}});root.addEventListener('click',async ev=>{const b=ev.target.closest('[data-economy-club],[data-economy-action]');if(!b||busy)return;if(b.dataset.economyClub){selected=b.dataset.economyClub;draw();return;}const amount=Math.round(Number(root.querySelector('[data-economy-amount]')?.value)*10000);busy=true;notice='正在保存…';draw();try{await saveEconomyAction({action:b.dataset.economyAction,amount,revision:peekSeason().revision});notice='已保存';}catch(error){notice=error.message;}finally{busy=false;if(current===token)draw();}});}
