import {formMarkup} from './presentation.js';
import {competitionStats} from './history.js';
import {clubIdentity,seniorTeams} from './team-directory.js';
import {registeredPlayer} from './registry.js';
import {readyManagedFixture} from './career.js';
import {clubs,YEAR} from '../world.js';
import {populationPlayer} from './population.js';
import {leagueSystems,getDivision,GLOBAL_CUP,METRO_CHAMPIONS,isMetroLeague} from './catalog.js';
import {loadSeason,peekSeason,readSeason,archivedYears,advanceDay,newSeason} from './store.js';
import {fixtureSides,tableFor,groupTable,nextDate,pendingMatches} from './runtime.js';
import {dateOf,addDays} from './calendar.js';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const club=id=>clubIdentity(id),clubName=id=>club(id)?.name||'待定';
export const competitions=[...leagueSystems.flatMap(s=>[...s.levels.map(d=>({id:d.id,name:d.name,kind:'league',system:s.id})),...(s.playoffs?[{id:`${s.id}-playoffs`,name:s.finalName,kind:'playoff',system:s.id}]:[])]),{...METRO_CHAMPIONS,kind:'championship',system:'closed'},{...GLOBAL_CUP,kind:'global'}];
export const competitionName=id=>competitions.find(c=>c.id===id)?.name||id;
const badge=id=>`<span class="hub-crest" aria-hidden="true">${esc(club(id)?.name.slice(0,2)||'待')}</span>`;
const teamLink=id=>id?`<a href="#squad/${esc(id)}">${esc(clubName(id))}</a>`:'待定';
const eventName=e=>e.kind==='global'?`${GLOBAL_CUP.name}举办窗口 · 国内休赛`:e.name;
const md=date=>`${Number(date.slice(5,7))} 月 ${Number(date.slice(8))} 日`;
const options=(list,value)=>list.map(([id,name])=>`<option value="${esc(id)}" ${String(value)===String(id)?'selected':''}>${esc(name)}</option>`).join('');
let root=null,season=null,years=[],cleanup=()=>{},generation=0,running=false,notice='',progress='',viewYear=null;
let clubFilter='all',month=3,selectedDate=null,bracketFilter='metro-champions';
const tabs=[['overview','赛事总览'],['schedule','赛程与赛果'],['calendar','月历'],['table','积分榜'],['bracket','淘汰赛'],['summary','赛季结果']];
function context(){const [,tab='overview',competition='all']=location.hash.split('/');return {tab:tabs.some(([k])=>k===tab)?tab:'schedule',competition:competitions.some(c=>c.id===competition)?competition:'all'};}
const href=(tab,comp=context().competition)=>`#match/${tab}/${comp}${clubFilter==='all'?'':`/${clubFilter}`}`;
function filtered(){const {competition}=context();return season.fixtures.filter(m=>!m.bye&&(competition==='all'||m.competition===competition)&&(clubFilter==='all'||Object.values(fixtureSides(season,m)).includes(clubFilter)));}
function monthFixtures(){return filtered().filter(m=>Number(m.date.slice(5,7))===month);}
function titleFor(m){if(m.kind==='championship-group')return `争冠组第 ${m.round} 轮`;if(m.kind==='league')return `第 ${m.round} 轮`;if(m.kind==='group')return `${m.group} 组 · 第 ${m.round} 轮`;const last=Math.max(...season.fixtures.filter(f=>f.competition===m.competition&&f.kind===m.kind).map(f=>f.round));return last-m.round===0?'决赛':last-m.round===1?'半决赛':last-m.round===2?'四分之一决赛':m.kind==='global-ko'?'十六强':`第 ${m.round} 轮`;}
function participant(id){if(!id)return '轮空';if(club(id))return clubName(id);if(id.startsWith('rank:')){const [,d,n]=id.split(':');return `${competitionName(d)}第 ${n} 名`; }if(id.startsWith('group:'))return `${id.split(':')[1]} 组第 ${id.split(':')[2]} 名`;return '前轮胜者';}
function header(){const current=peekSeason(),isCurrent=season.year===current.year,done=season.fixtures.filter(m=>m.score).length,total=season.fixtures.filter(m=>!m.bye).length,next=nextDate(current);return `<header class="hub-heading"><div><span class="hub-eyebrow">${season.year} 赛季 · ${isCurrent?(season.summary?'已结束':'进行中'):'赛季档案'}</span><h1>${clubFilter!=='all'?esc(clubName(clubFilter)):context().competition==='all'?'比赛中心':esc(competitionName(context().competition))}</h1></div><div class="hub-date"><span>殖民历 · 当前日期</span><strong>${current.year} / ${current.date.slice(5).replace('-',' / ')}</strong></div><div class="hub-progress"><strong>${done.toLocaleString()} <small>/ ${total.toLocaleString()}</small></strong><span>已完成比赛</span><progress value="${done}" max="${total}" aria-label="赛季完成场次"></progress></div></header><details class="hub-time-tools" ${running||notice?'open':''}><summary>赛历操作</summary><div class="hub-actions"><div>${running?'<button class="football-primary" data-hub="pause">暂停推进</button>':isCurrent&&next?`<button class="football-primary" data-hub="next">推进至 ${md(next)} →</button><label class="hub-until">推进至日期<input type="date" data-until value="${current.date}" min="${current.date}" max="${dateOf(current.year,12,31)}"></label><button data-hub="until">推进</button>`:isCurrent?`<button class="football-primary" data-hub="new">进入 ${current.year+1} 赛季 →</button>`:''}</div>${current.manager?'<a class="football-link" href="#manager">经理首页 ↗</a>':''}<a class="football-link" href="#friendly">友谊赛 ↗</a></div><p class="hub-status" role="status" aria-live="polite">${esc(progress||notice||'本地自动存档 · 星球标准时')}</p></details>`;}
function filters(){const {competition,tab}=context();return `<nav class="hub-tabs" aria-label="比赛中心栏目">${tabs.map(([key,label])=>`<a href="${href(key)}" ${tab===key?'aria-current="page"':''}>${label}</a>`).join('')}</nav><div class="hub-filters"><label>赛季<select aria-label="赛季" data-year ${running?'disabled':''}>${options([...new Set([...years,peekSeason().year])].sort((a,b)=>b-a).map(y=>[y,`${y} 赛季`]),season.year)}</select></label><label>赛事<select aria-label="赛事" data-competition>${options([['all','全部赛事'],...competitions.map(c=>[c.id,c.name])],competition)}</select></label><label>球队<select aria-label="球队" data-club>${options([['all','全部球队'],...clubs.filter(c=>competition==='all'||season.fixtures.some(m=>m.competition===competition&&[m.home,m.away].includes(c.id))||season.members[competition.replace('-playoffs','')]?.includes(c.id)||competition==='metro-champions'&&isMetroLeague(c.league)).map(c=>[c.id,c.name])],clubFilter)}</select></label><a class="football-link" href="#leagues/all">赛制与名额 ↗</a></div>`;}
function monthNav(){return `<nav class="hub-months" aria-label="月份">${Array.from({length:12},(_,i)=>`<button data-month="${i+1}" ${month===i+1?'aria-current="date"':''}>${i+1} 月</button>`).join('')}</nav>`;}
function matchRow(m){const {home,away}=fixtureSides(season,m);return `<article class="hub-match"><span class="hub-time">${m.score?'已结束':m.time}<small>${m.neutral?'中立场':'主 / 客'}</small></span><div class="hub-home">${home?teamLink(home):esc(participant(m.home))}${home?badge(home):''}</div><button class="hub-score ${m.score?'played':''}" data-report="${esc(m.id)}" aria-label="${esc(clubName(home))} 对 ${esc(clubName(away))} 比赛详情">${m.score?m.score.join(' : '):'VS'}${m.shootout?`<small>点球 ${m.shootout.score.join(' : ')}</small>`:''}</button><div class="hub-away">${away?badge(away):''}${away?teamLink(away):esc(participant(m.away))}</div><span class="hub-round">${titleFor(m)}</span></article>`;}
function clubSchedule(){const fixtures=monthFixtures();return `${monthNav()}<div class="hub-day-heading"><h2>${esc(clubName(clubFilter))} · ${month} 月赛程</h2><span>${fixtures.length} 场 · 比分为主队 : 客队</span></div><div class="desk-table-scroll"><table class="desk-table fixture-table"><thead><tr><th>日期</th><th>时间</th><th>对手</th><th>场地</th><th>结果</th><th>赛事</th><th>阶段</th></tr></thead><tbody>${fixtures.map(m=>{const sides=fixtureSides(season,m),home=sides.home===clubFilter,other=home?sides.away:sides.home,side=home?0:1,result=!m.score?'':m.score[side]>m.score[1-side]?'win':m.score[side]<m.score[1-side]?'loss':'draw';return `<tr class="${m.date===(selectedDate||season.date)?'is-own':''}"><td>${m.date}</td><td>${m.time}</td><td>${teamLink(other)}</td><td>${m.neutral?'中立':home?'主':'客'}</td><td><button class="fixture-result form-${result}" data-report="${esc(m.id)}">${m.score?`${{win:'胜',loss:'负',draw:'平'}[result]} ${m.score.join(' : ')}`:'待赛'}</button></td><td><a href="${href('overview',m.competition)}">${esc(competitionName(m.competition))}</a></td><td>${titleFor(m)}</td></tr>`;}).join('')||'<tr><td colspan="7" class="desk-empty">本月无比赛安排</td></tr>'}</tbody></table></div>`;}
function overview(){
 const requested=context().competition,id=requested==='all'?(season.manager?Object.keys(season.members).find(d=>season.members[d].includes(season.manager.clubId)):'closed'):requested,d=getDivision(id),data=competitionStats(season,id),fixtures=season.fixtures.filter(m=>m.competition===id&&!m.bye),next=fixtures.find(m=>!m.score)?.date||fixtures.at(-1)?.date,day=fixtures.filter(m=>m.date===next),table=d?tableFor(season,id):[];
 const panel=(title,body,cls='')=>`<section class="desk-panel ${cls}"><h2>${title}</h2>${body}</section>`,board=(key,label)=>{const rows=data.leaderboards[key].filter(p=>p[key]>0).slice(0,4);return `<div class="competition-board"><h3>${label}</h3>${rows.map((p,i)=>`<a href="#squad/${p.clubs.at(-1)}/${p.id}"><span>${i+1}</span><strong>${esc(p.name)}</strong><b>${key==='contribution'?p[key].toFixed(1):p[key]}</b></a>`).join('')||'<p class="desk-empty">赛季暂无数据</p>'}</div>`;};
 return `<div class="competition-banner"><div><small>${season.year} 赛季 · ${d?'联赛':'杯赛'}</small><h2>${esc(competitionName(id))}</h2></div><dl><div><dt>参赛球队</dt><dd>${d?.teams||(id==='global-cup'?16:id==='metro-champions'?12:leagueSystems.find(system=>`${system.id}-playoffs`===id)?.playoffs?.teams||'—')}</dd></div><div><dt>比赛场次</dt><dd>${data.matches} / ${fixtures.length}</dd></div><div><dt>总进球</dt><dd>${data.goals}</dd></div><div><dt>当前阶段</dt><dd>${day[0]?titleFor(day[0]):'等待赛程'}</dd></div></dl></div>
 <div class="competition-desk-grid">${panel(d?'联赛积分榜':'赛事阶段',d?`<table class="desk-table compact-standings"><thead><tr><th>名次</th><th>球队</th><th>赛</th><th>分</th></tr></thead><tbody>${table.map(r=>`<tr class="${r.id===season.manager?.clubId?'is-own':''}"><td>${r.played?r.rank:'—'}</td><td><a href="#squad/${r.id}/overview">${esc(clubName(r.id))}</a></td><td>${r.played}</td><td><b>${r.points}</b></td></tr>`).join('')}</tbody></table><a class="desk-panel-link" href="${href('table',id)}">完整积分榜</a>`:`<div class="competition-stage">${fixtures.filter(m=>['playoff','global-ko','championship-ko'].includes(m.kind)).slice(-7).map(m=>{const sides=fixtureSides(season,m);return `<button data-report="${m.id}"><small>${titleFor(m)} · ${md(m.date)}</small><span>${esc(sides.home?clubName(sides.home):participant(m.home))}</span><b>${m.score?m.score.join(' : '):'对'}</b><span>${esc(sides.away?clubName(sides.away):participant(m.away))}</span></button>`;}).join('')||'<p class="desk-empty">淘汰赛对阵尚未确定</p>'}</div><a class="desk-panel-link" href="${href('bracket',id)}">完整淘汰赛签表</a>`,'competition-standings')}
 ${panel('比赛日程',`<div class="competition-match-date">${next?`${md(next)} · ${day.length} 场`:'暂无赛程'}</div>${day.slice(0,6).map(matchRow).join('')}<a class="desk-panel-link" href="${href('schedule',id)}">全部赛程与赛果</a>`,'competition-fixtures')}
 ${panel('赛事信息',`<dl class="desk-facts"><div><dt>赛制</dt><dd>${d?d.legs===2?'主客场双循环':'单循环':id==='global-cup'?'小组赛 + 单场淘汰':id==='metro-champions'?'争冠组 + 单场淘汰':'单场淘汰'}</dd></div><div><dt>${d?'积分规则':'决胜规则'}</dt><dd>${d?'胜 3 · 平 1 · 负 0':'加时 / 点球'}</dd></div><div><dt>赛季</dt><dd>${season.year}</dd></div><div><dt>冠军</dt><dd>${esc(clubName(season.summary?.champions.find(c=>c.competition===id)?.id))}</dd></div></dl><a class="desk-panel-link" href="#leagues/all">赛事体系与资格</a>`,'competition-info')}
 ${panel('球员数据',`<div class="competition-boards">${board('goals','进球')}${board('assists','助攻')}${board('saves','扑救')}${board('contribution','赛事贡献分')}</div>`,'competition-statistics')}
 ${panel('俱乐部',`<div class="competition-clubs">${(season.members[id]||[...new Set(fixtures.flatMap(m=>Object.values(fixtureSides(season,m))).filter(Boolean))]).slice(0,6).map(id=>`<a href="#squad/${id}/overview">${esc(clubName(id))}<span>俱乐部总览</span></a>`).join('')||'<p class="desk-empty">参赛队尚未确定</p>'}</div>`,'competition-clubs-panel')}</div>`;
}
function schedule(){if(clubFilter!=='all')return clubSchedule();const fixtures=monthFixtures(),dates=[...new Set(fixtures.map(m=>m.date))];if(!selectedDate||Number(selectedDate.slice(5,7))!==month||!dates.includes(selectedDate))selectedDate=dates.find(d=>d>=season.date)||dates[0]||dateOf(season.year,month,1);const todays=fixtures.filter(m=>m.date===selectedDate),comps=[...new Set(todays.map(m=>m.competition))];const milestones=season.calendar.events.filter(e=>Number(e.date.slice(5,7))===month);return `${monthNav()}<div class="hub-date-strip" aria-label="比赛日">${dates.map(date=>`<button data-day="${date}" ${selectedDate===date?'aria-pressed="true"':'aria-pressed="false"'}><small>${['日','一','二','三','四','五','六'][new Date(`${date}T12:00:00Z`).getUTCDay()]}</small><strong>${Number(date.slice(8))}</strong><span>${fixtures.filter(m=>m.date===date).length} 场</span></button>`).join('')||'<span>本月无符合条件的比赛</span>'}</div>${comps.length?`<div class="hub-day-heading"><h2>${md(selectedDate)}</h2><span>${todays.filter(m=>m.score).length} / ${todays.length} 场已结束</span></div>${comps.map(comp=>`<section class="hub-match-group"><h3><span class="hub-dot ${competitions.find(c=>c.id===comp).kind}"></span>${esc(competitionName(comp))}<a href="${href('table',comp)}">${getDivision(comp)?'积分榜 ↗':'赛事详情 ↗'}</a></h3>${todays.filter(m=>m.competition===comp).map(matchRow).join('')}</section>`).join('')}`:`<section class="hub-empty"><h2>${month} 月</h2>${milestones.map(e=>`<p><time>${md(e.date)}${e.end?`—${md(e.end)}`:''}</time>${eventName(e)}</p>`).join('')||'<p>没有符合条件的赛程</p>'}</section>`}`;}
function calendar(){
 const all=filtered(),first=dateOf(season.year,month,1),days=new Date(Date.UTC(season.year,month,0)).getUTCDate(),offset=(new Date(`${first}T12:00:00Z`).getUTCDay()+6)%7;
 return `${monthNav()}<div class="hub-day-heading"><h2>${season.year} 年 ${month} 月</h2><span>${clubFilter==='all'?'全部球队':esc(clubName(clubFilter))} · ${all.filter(m=>Number(m.date.slice(5,7))===month).length} 场比赛</span></div><div class="calendar-scroll"><div class="hub-calendar">${['一','二','三','四','五','六','日'].map(x=>`<div class="weekday">星期${x}</div>`).join('')}${'<div class="calendar-blank"></div>'.repeat(offset)}${Array.from({length:days},(_,i)=>{const date=dateOf(season.year,month,i+1),fs=all.filter(m=>m.date===date),events=season.calendar.events.filter(e=>e.date===date);return `<button data-calendar-day="${date}" aria-label="${month} 月 ${i+1} 日 · ${fs.length} 场比赛" class="${date===season.date?'today':''}"><b>${i+1}${date===season.date?'<em>今天</em>':''}</b>${events.map(e=>`<small class="calendar-window">${esc(eventName(e))}</small>`).join('')}${fs.slice(0,3).map(m=>{const {home,away}=fixtureSides(season,m);return `<span class="calendar-match ${m.score?'completed':''}"><small>${esc(competitionName(m.competition))} · ${m.score?m.score.join(' : '):m.time}</small><strong>${esc(clubFilter==='all'?`${clubName(home)} / ${clubName(away)}`:clubName(home===clubFilter?away:home))}</strong><small>${clubFilter==='all'?'':home===clubFilter?'主场':'客场'}</small></span>`;}).join('')}${fs.length>3?`<span class="calendar-more">另 ${fs.length-3} 场比赛</span>`:''}</button>`;}).join('')}${'<div class="calendar-blank"></div>'.repeat((7-(offset+days)%7)%7)}</div></div>`;
}
function tableMarkup(rows,d=null,advance=2){const sys=leagueSystems.find(s=>s.levels.some(l=>l.id===d?.id));return `<div class="league-table-wrap"><table class="league-table hub-table"><thead><tr><th>名次</th><th>球队</th><th>赛</th><th>胜</th><th>平</th><th>负</th><th>进 / 失</th><th>净胜</th><th>积分</th><th>近五场</th><th>席位</th></tr></thead><tbody>${rows.map((r,i)=>{const zone=!r.played?'':d?.relegation&&i>=d.teams-d.relegation?'降级区':d?.promotion&&i<d.promotion.automatic?'直接升级':d&&isMetroLeague(sys?.id)&&i<4?'星冠季后赛':sys?.playoffs&&i<sys.playoffs.teams?'季后赛':d?.tier===1&&!isMetroLeague(sys?.id)&&!sys.playoffs&&i<sys.globalSlots?'全球冠军杯资格区':!d&&i<advance?'晋级区':'';return `<tr class="${zone==='降级区'?'zone-down':zone?'zone-up':''} ${r.id===clubFilter?'focused-team':''}"><td>${r.played?r.rank:'—'}</td><td>${badge(r.id)}${teamLink(r.id)}</td><td>${r.played}</td><td>${r.won}</td><td>${r.drawn}</td><td>${r.lost}</td><td>${r.gf} / ${r.ga}</td><td>${r.gd>0?'+':''}${r.gd}</td><td><strong>${r.points}</strong></td><td>${formMarkup(season,r.id,d?.id||context().competition)}</td><td><small>${zone||'—'}</small></td></tr>`;}).join('')}</tbody></table></div>`;}
function tables(){const {competition}=context();const regular=leagueSystems.flatMap(s=>s.levels).filter(d=>competition==='all'||d.id===competition||`${d.id}-playoffs`===competition);return regular.map(d=>`<section class="hub-table-section"><h2>${d.name}</h2>${tableMarkup(tableFor(season,d.id),d)}</section>`).join('')+(competition==='all'||competition==='metro-champions'?`<section class="hub-table-section"><h2>星冠季后赛 · 争冠组</h2>${season.fixtures.some(m=>m.kind==='league'&&isMetroLeague(m.competition)&&!m.score)?'<p>三联赛常规赛结束后确定参赛队</p>':tableMarkup(tableFor(season,'metro-champions'),null,4)}</section>`:'')+(competition==='all'||competition==='global-cup'?season.groups.map(g=>`<section class="hub-table-section"><h2>全球冠军杯 · ${g.id}组</h2>${tableMarkup(groupTable(season,g.id))}</section>`).join('')||'<p>本赛季不举办全球冠军杯</p>':'');}

function brackets(){const {competition}=context();const available=competitions.filter(c=>c.kind!=='league'),system=leagueSystems.find(s=>s.levels.some(d=>d.id===competition));if(system&&!isMetroLeague(system.id)&&!system.playoffs)return '<section class="hub-empty"><h2>本联赛无淘汰赛</h2><p>冠军与升降级按常规赛排名确定</p></section>';let id=competition==='all'?bracketFilter:system?(isMetroLeague(system.id)?'metro-champions':`${system.id}-playoffs`):competition;const fs=season.fixtures.filter(m=>m.competition===id&&!['group','championship-group'].includes(m.kind)),rounds=[...new Set(fs.map(m=>m.round))];return `<div class="hub-bracket-toolbar"><label>淘汰赛签表<select aria-label="淘汰赛签表" data-bracket>${options(available.map(c=>[c.id,c.name]),id)}</select></label><span>${id==='global-cup'?'单场 · 全部中立场':id==='metro-champions'?'争冠组前四 · 半决赛高排名主场 · 决赛中立场':id.endsWith('-playoffs')?'单场 · 决赛中立场，其余高排名主场':'单场 · 决赛中立场'}</span></div>${id==='global-cup'?`<p class="hub-caption">资格来源：${season.qualificationSource} · <a href="${href('table','global-cup')}">小组积分榜 ↗</a></p>`:''}${!fs.length?'<p>本赛季无此项淘汰赛</p>':''}<div class="hub-bracket">${rounds.map(round=>`<section><h3>${titleFor(fs.find(m=>m.round===round))}<small>${md(fs.find(m=>m.round===round).date)}</small></h3><div class="bracket-round">${fs.filter(m=>m.round===round).map(m=>{const {home,away}=fixtureSides(season,m);return `<button class="bracket-match ${m.bye?'bye':''}" data-report="${esc(m.id)}"><div class="${home&&m.winner===home?'winner':''}"><span>${esc(home?clubName(home):participant(m.home))}</span><b>${m.score?.[0]??'—'}</b></div><div class="${away&&m.winner===away?'winner':''}"><span>${esc(away?clubName(away):participant(m.away))}</span><b>${m.score?.[1]??'—'}</b></div><small>${m.bye?'轮空':m.shootout?`点球 ${m.shootout.score.join(':')}`:m.neutral?'中立场':m.kind==='playoff'?'高排名主场':'主 / 客'}</small></button>`;}).join('')}</div></section>`).join('')}</div>`;}
function summary(){const s=season.summary,{competition}=context(),matchesClub=id=>clubFilter==='all'||id===clubFilter;if(!s)return `<section class="hub-empty"><h2>赛季尚未结算</h2><p>12 月 1 日确认冠军、升降级及下一赛季资格。</p><p>${pendingMatches(season).length.toLocaleString()} 场待赛</p><a class="football-link" href="${href('bracket')}">查看淘汰赛签表 ↗</a></section>`;return `<div class="hub-summary"><section><h2>升降级 · ${season.year+1} 赛季</h2>${s.movements.filter(m=>matchesClub(m.id)&&(competition==='all'||m.from===competition||m.to===competition||competition===`${m.from}-playoffs`)).map(m=>`<div class="movement"><b class="${m.kind}">${m.kind==='up'?'↑ 升级':'↓ 降级'}</b>${teamLink(m.id)}<span>${competitionName(m.from)} → ${competitionName(m.to)}</span></div>`).join('')}</section><section><h2>赛季冠军</h2>${s.champions.filter(c=>matchesClub(c.id)&&(competition==='all'||c.competition===competition)).map(c=>`<div class="movement"><span>${competitionName(c.competition)}</span>${teamLink(c.id)}</div>`).join('')}<h2>${season.year+1} 全球冠军杯候选资格</h2>${s.qualifiers.filter(c=>matchesClub(c.id)&&(competition==='all'||competition==='global-cup'||competition==='metro-champions'&&c.system==='closed'||isMetroLeague(competition)&&club(c.id)?.league===competition||!isMetroLeague(competition)&&c.system===competition)).map(c=>`<div class="movement">${teamLink(c.id)}<span>${c.system==='closed'?'星冠季后赛':competitionName(c.system)} · 年度第 ${c.rank} 名</span></div>`).join('')}</section></div>`;}
function draw(){if(!root||!season)return;const tab=context().tab;root.classList.toggle('hub-overview-mode',tab==='overview');root.innerHTML=`${header()}${filters()}${tab==='overview'?overview():tab==='calendar'?calendar():tab==='table'?tables():tab==='bracket'?brackets():tab==='summary'?summary():schedule()}<dialog class="hub-report" aria-label="比赛详情"><div id="hub-report-content"></div></dialog>`;const date=document.querySelector('.app-topbar .date');if(date)date.innerHTML=`<span>殖民历</span> ${peekSeason().year} <span>年 ${md(peekSeason().date)}</span>`;}
function report(id){const m=season.fixtures.find(m=>m.id===id);if(!m)return;const {home,away}=fixtureSides(season,m),dialog=root.querySelector('dialog'),data=m.report;dialog.querySelector('#hub-report-content').innerHTML=`<button data-close class="report-close" aria-label="关闭比赛详情">✕</button><p>${competitionName(m.competition)} · ${titleFor(m)}</p><div class="report-score"><div>${badge(home)}${teamLink(home)}</div><strong>${m.score?m.score.join(' : '):'VS'}</strong><div>${badge(away)}${teamLink(away)}</div></div><p>${md(m.date)} · ${m.time} · ${m.bye?'轮空':m.score?'已结束':'未开赛'}${m.neutral?' · 中立场':''}${m.shootout?` · 点球 ${m.shootout.score.join(' : ')}`:''}</p>${data?`<div class="report-stats">${[['shots','射门'],['onTarget','射正'],['xG','预期进球'],['corners','角球'],['fouls','犯规'],['yellow','黄牌'],['red','红牌']].map(([key,label])=>`<div><b>${key==='xG'?data.stats[0][key].toFixed(2):data.stats[0][key]}</b><span>${label}</span><b>${key==='xG'?data.stats[1][key].toFixed(2):data.stats[1][key]}</b></div>`).join('')}</div><h3>关键事件</h3>${data.events.map(e=>{const p=populationPlayer(season,e.player),teamId=p?.club||p?.lastClub||[home,away][e.side];return `<div class="report-event"><time>${e.minute}′</time><a href="#squad/${teamId}/${p?.id}">${esc(p?.name||'球员')}</a><span>${e.type==='shot'?'进球':e.type==='red'?'红牌':`伤退 · ${e.days} 天`}</span></div>`;}).join('')||'<p>无进球、红牌或伤退</p>'}`:`<p>${m.bye?'本轮自动晋级':home&&away?'等待比赛日':'前序赛事结束后确定对阵'}</p>`}`;dialog.showModal();}
export function renderHub(){return '<section class="football-page season-hub" id="season-hub"><p role="status">正在读取赛季…</p></section>';}
export function disposeHub(){running=false;generation++;cleanup();root=null;}
export async function mountHub(){root=document.querySelector('#season-hub');const routeClub=location.hash.split('/')[3];if(routeClub&&club(routeClub))clubFilter=routeClub;else clubFilter='all';const token=++generation;try{const current=await loadSeason();years=await archivedYears();if(token!==generation)return;season=viewYear&&viewYear!==current.year?await readSeason(viewYear):current;if(token!==generation)return;if(context().tab==='overview'&&context().competition==='all'){location.replace(href('overview',season.manager?Object.keys(season.members).find(d=>season.members[d].includes(season.manager.clubId)):'closed'));return;}draw();}catch(error){if(token===generation&&root)root.innerHTML=`<h1>${clubFilter!=='all'?esc(clubName(clubFilter)):context().competition==='all'?'比赛中心':esc(competitionName(context().competition))}</h1><p role="alert">${esc(error.message)}</p><button onclick="location.reload()">重新读取</button>`;return;}
 const click=async ev=>{const b=ev.target.closest('button');if(!b)return;
  if(b.hasAttribute('data-close')){root.querySelector('dialog').close();return;}
  if(b.dataset.report){report(b.dataset.report);return;}
  if(b.dataset.month){month=Number(b.dataset.month);selectedDate=null;draw();return;}
  if(b.dataset.day){selectedDate=b.dataset.day;draw();return;}
  if(b.dataset.calendarMonth){month=Number(b.dataset.calendarMonth);draw();return;}
  if(b.dataset.calendarDay){selectedDate=b.dataset.calendarDay;month=Number(selectedDate.slice(5,7));location.hash=href('schedule');return;}
  if(b.dataset.hub==='pause'){running=false;progress='正在暂停…';draw();return;}
  if(!b.dataset.hub||running)return;
  let target=b.dataset.hub==='until'?root.querySelector('[data-until]').value:nextDate(peekSeason());
  if(b.dataset.hub!=='new'&&(!target||target<peekSeason().date||target>dateOf(peekSeason().year,12,31))){notice='请选择本赛季内的未来日期';draw();return;}
  running=true;notice='';progress='正在推进赛历…';draw();
  try{if(b.dataset.hub==='new'){season=await newSeason();viewYear=null;month=3;selectedDate=null;years=await archivedYears();}else{while(running&&generation===token&&(peekSeason().date<target||pendingMatches(peekSeason()).some(m=>m.date===target))){const next=nextDate(peekSeason()),date=next&&next<target?next:target;season=await advanceDay(date,{shouldStop:()=>!running||generation!==token,onProgress:(n,total)=>{progress=`${md(date)} · ${n} / ${total} 场`;const status=root?.querySelector('.hub-status');if(status)status.textContent=progress;}});if(generation===token){month=Number(season.date.slice(5,7));selectedDate=season.date;draw();}if(readyManagedFixture(season)||season.activeMatch)break;await new Promise(r=>setTimeout(r,0));}}notice=readyManagedFixture(peekSeason())?'已到本队比赛日，请前往经理首页执教':'已保存';}catch(error){notice=error.message;season=peekSeason();}finally{running=false;progress='';if(generation===token)draw();}
 };
 const change=async ev=>{const el=ev.target;if(el.hasAttribute('data-competition')){clubFilter='all';selectedDate=null;location.hash=href(context().tab,el.value);}else if(el.hasAttribute('data-club')){clubFilter=el.value;selectedDate=null;const next=href(context().tab);if(location.hash!==next)location.hash=next;else draw();}else if(el.hasAttribute('data-year')){try{viewYear=Number(el.value);season=await readSeason(viewYear);if(generation===token){selectedDate=null;draw();}}catch(e){notice=e.message;draw();}}else if(el.hasAttribute('data-bracket')){bracketFilter=el.value;location.hash=href('bracket',el.value);}};
 root.addEventListener('click',click);root.addEventListener('change',change);const mounted=root;cleanup=()=>{mounted.removeEventListener('click',click);mounted.removeEventListener('change',change);};
}
