import {registeredPlayer} from './registry.js';
import {readyManagedFixture} from './career.js';
import {clubs,YEAR} from '../world.js';
import {footballTeams} from '../football/data.js';
import {leagueSystems,getDivision,GLOBAL_CUP} from './catalog.js';
import {loadSeason,peekSeason,readSeason,archivedYears,advanceDay,newSeason} from './store.js';
import {fixtureSides,tableFor,groupTable,nextDate,pendingMatches} from './runtime.js';
import {dateOf,addDays} from './calendar.js';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const club=id=>clubs.find(c=>c.id===id),clubName=id=>club(id)?.name||'待定';
export const competitions=[...leagueSystems.flatMap(s=>[...s.levels.map(d=>({id:d.id,name:d.name,kind:'league',system:s.id})),...(s.cup?[{...s.cup,kind:'cup',system:s.id}]:[]),...s.levels.filter(d=>d.promotion||s.id==='closed').map(d=>({id:`${d.id}-playoffs`,name:s.id==='closed'?'星冠季后赛':`${d.name}升级附加赛`,kind:'playoff',system:s.id}))]),{...GLOBAL_CUP,kind:'global'}];
export const competitionName=id=>competitions.find(c=>c.id===id)?.name||id;
const badge=id=>`<span class="hub-crest" aria-hidden="true">${esc(club(id)?.name.slice(0,2)||'待')}</span>`;
const teamLink=id=>id?`<a href="#squad/${esc(id)}">${esc(clubName(id))}</a>`:'待定';
const md=date=>`${Number(date.slice(5,7))} 月 ${Number(date.slice(8))} 日`;
const options=(list,value)=>list.map(([id,name])=>`<option value="${esc(id)}" ${String(value)===String(id)?'selected':''}>${esc(name)}</option>`).join('');
let root=null,season=null,years=[],cleanup=()=>{},generation=0,running=false,notice='',progress='',viewYear=null;
let clubFilter='all',month=3,selectedDate=null,bracketFilter='closed-playoffs';
const tabs=[['schedule','赛程与赛果'],['calendar','全年赛历'],['table','积分榜'],['bracket','淘汰赛'],['summary','赛季结果']];
function context(){const [,tab='schedule',competition='all']=location.hash.split('/');return {tab:tabs.some(([k])=>k===tab)?tab:'schedule',competition:competitions.some(c=>c.id===competition)?competition:'all'};}
const href=(tab,comp=context().competition)=>`#match/${tab}/${comp}`;
function filtered(){const {competition}=context();return season.fixtures.filter(m=>!m.bye&&(competition==='all'||m.competition===competition)&&(clubFilter==='all'||Object.values(fixtureSides(season,m)).includes(clubFilter)));}
function monthFixtures(){return filtered().filter(m=>Number(m.date.slice(5,7))===month);}
function titleFor(m){if(m.kind==='league')return `第 ${m.round} 轮`;if(m.kind==='group')return `${m.group} 组 · 第 ${m.round} 轮`;const last=Math.max(...season.fixtures.filter(f=>f.competition===m.competition&&f.kind===m.kind).map(f=>f.round));return last-m.round===0?'决赛':last-m.round===1?'半决赛':last-m.round===2?'四分之一决赛':m.kind==='global-ko'?'十六强':`第 ${m.round} 轮`;}
function participant(id){if(!id)return '轮空';if(club(id))return clubName(id);if(id.startsWith('rank:')){const [,d,n]=id.split(':');return `常规赛第 ${n} 名`; }if(id.startsWith('group:'))return `${id.split(':')[1]} 组第 ${id.split(':')[2]} 名`;return '前轮胜者';}
function header(){const current=peekSeason(),isCurrent=season.year===current.year,done=season.fixtures.filter(m=>m.score).length,total=season.fixtures.filter(m=>!m.bye).length,next=nextDate(current);return `<header class="hub-heading"><div><span class="hub-eyebrow">${season.year} 赛季 · ${isCurrent?(season.summary?'已结束':'进行中'):'赛季档案'}</span><h1>比赛中心</h1></div><div class="hub-date"><span>殖民历 · 当前日期</span><strong>${current.year} / ${current.date.slice(5).replace('-',' / ')}</strong></div><div class="hub-progress"><strong>${done.toLocaleString()} <small>/ ${total.toLocaleString()}</small></strong><span>已完成比赛</span><progress value="${done}" max="${total}" aria-label="赛季完成场次"></progress></div></header><div class="hub-actions"><div>${running?'<button class="football-primary" data-hub="pause">暂停推进</button>':isCurrent&&next?`<button class="football-primary" data-hub="next">推进至 ${md(next)} →</button><label class="hub-until">推进至日期<input type="date" data-until value="${current.date}" min="${current.date}" max="${dateOf(current.year,12,31)}"></label><button data-hub="until">推进</button>`:isCurrent?`<button class="football-primary" data-hub="new">进入 ${current.year+1} 赛季 →</button>`:''}</div>${current.manager?'<a class="football-link" href="#manager">经理首页 ↗</a>':''}<a class="football-link" href="#friendly">友谊赛 ↗</a></div><p class="hub-status" role="status" aria-live="polite">${esc(progress||notice||'本地自动存档 · 星球标准时')}</p>`;}
function filters(){const {competition,tab}=context();return `<nav class="hub-tabs" aria-label="比赛中心栏目">${tabs.map(([key,label])=>`<a href="${href(key)}" ${tab===key?'aria-current="page"':''}>${label}</a>`).join('')}</nav><div class="hub-filters"><label>赛季<select aria-label="赛季" data-year ${running?'disabled':''}>${options([...new Set([...years,peekSeason().year])].sort((a,b)=>b-a).map(y=>[y,`${y} 赛季`]),season.year)}</select></label><label>赛事<select aria-label="赛事" data-competition>${options([['all','全部赛事'],...competitions.map(c=>[c.id,c.name])],competition)}</select></label><label>球队<select aria-label="球队" data-club>${options([['all','全部球队'],...clubs.filter(c=>competition==='all'||season.fixtures.some(m=>m.competition===competition&&[m.home,m.away].includes(c.id))||season.members[competition.replace('-playoffs','')]?.includes(c.id)).map(c=>[c.id,c.name])],clubFilter)}</select></label><a class="football-link" href="#leagues/all">赛制与名额 ↗</a></div>`;}
function monthNav(){return `<nav class="hub-months" aria-label="月份">${Array.from({length:12},(_,i)=>`<button data-month="${i+1}" ${month===i+1?'aria-current="date"':''}>${i+1} 月</button>`).join('')}</nav>`;}
function matchRow(m){const {home,away}=fixtureSides(season,m);return `<article class="hub-match"><span class="hub-time">${m.score?'已结束':m.time}<small>${m.neutral?'中立场':'主 / 客'}</small></span><div class="hub-home">${teamLink(home)}${badge(home)}</div><button class="hub-score ${m.score?'played':''}" data-report="${esc(m.id)}" aria-label="${esc(clubName(home))} 对 ${esc(clubName(away))} 比赛详情">${m.score?m.score.join(' : '):'VS'}${m.shootout?`<small>点球 ${m.shootout.score.join(' : ')}</small>`:''}</button><div class="hub-away">${badge(away)}${teamLink(away)}</div><span class="hub-round">${titleFor(m)}</span></article>`;}
function schedule(){const fixtures=monthFixtures(),dates=[...new Set(fixtures.map(m=>m.date))];if(!selectedDate||Number(selectedDate.slice(5,7))!==month||!dates.includes(selectedDate))selectedDate=dates.find(d=>d>=season.date)||dates[0]||dateOf(season.year,month,1);const todays=fixtures.filter(m=>m.date===selectedDate),comps=[...new Set(todays.map(m=>m.competition))];const milestones=season.calendar.events.filter(e=>Number(e.date.slice(5,7))===month);return `${monthNav()}<div class="hub-date-strip" aria-label="比赛日">${dates.map(date=>`<button data-day="${date}" ${selectedDate===date?'aria-pressed="true"':'aria-pressed="false"'}><small>${['日','一','二','三','四','五','六'][new Date(`${date}T12:00:00Z`).getUTCDay()]}</small><strong>${Number(date.slice(8))}</strong><span>${fixtures.filter(m=>m.date===date).length} 场</span></button>`).join('')||'<span>本月无符合条件的比赛</span>'}</div>${comps.length?`<div class="hub-day-heading"><h2>${md(selectedDate)}</h2><span>${todays.filter(m=>m.score).length} / ${todays.length} 场已结束</span></div>${comps.map(comp=>`<section class="hub-match-group"><h3><span class="hub-dot ${competitions.find(c=>c.id===comp).kind}"></span>${esc(competitionName(comp))}<a href="${href('table',comp)}">${getDivision(comp)?'积分榜 ↗':'赛事详情 ↗'}</a></h3>${todays.filter(m=>m.competition===comp).map(matchRow).join('')}</section>`).join('')}`:`<section class="hub-empty"><h2>${month} 月</h2>${milestones.map(e=>`<p><time>${md(e.date)}${e.end?`—${md(e.end)}`:''}</time>${e.name}</p>`).join('')||'<p>没有符合条件的赛程</p>'}</section>`}`;}
function calendar(){const all=filtered(),first=dateOf(season.year,month,1),days=Number(addDays(dateOf(season.year,month===12?12:month+1,1),month===12?30:-1).slice(8)),offset=(new Date(`${first}T12:00:00Z`).getUTCDay()+6)%7;return `<div class="hub-year">${Array.from({length:12},(_,i)=>{const n=i+1,fs=all.filter(m=>Number(m.date.slice(5,7))===n),events=season.calendar.events.filter(e=>Number(e.date.slice(5,7))===n);return `<button data-calendar-month="${n}" class="${n===month?'active':''}"><strong>${String(n).padStart(2,'0')}<small>月</small></strong><span>${fs.length?`${fs.filter(m=>m.score).length} / ${fs.length} 场`:'休赛 / 窗口'}</span><div>${events.map(e=>`<small class="calendar-event ${e.kind}">${e.name}</small>`).join('')||'<small>联赛进行中</small>'}</div></button>`;}).join('')}</div><div class="hub-day-heading"><h2>${month} 月赛历</h2><span>联赛 <i class="hub-dot league"></i> 杯赛 <i class="hub-dot cup"></i> 附加赛 <i class="hub-dot playoff"></i></span></div><div class="hub-calendar">${['一','二','三','四','五','六','日'].map(x=>`<div class="weekday">${x}</div>`).join('')}${'<div class="calendar-blank"></div>'.repeat(offset)}${Array.from({length:days},(_,i)=>{const date=dateOf(season.year,month,i+1),fs=all.filter(m=>m.date===date),events=season.calendar.events.filter(e=>e.date===date);return `<button data-calendar-day="${date}" class="${date===season.date?'today':''}"><b>${i+1}</b>${fs.length?`<span>${fs.length} 场</span><div>${[...new Set(fs.map(m=>m.kind))].map(k=>`<i class="hub-dot ${k}"></i>`).join('')}</div>`:''}${events.map(e=>`<small>${e.name}</small>`).join('')}</button>`;}).join('')}</div><section class="hub-calendar-events">${season.calendar.events.filter(e=>Number(e.date.slice(5,7))===month||e.end&&Number(e.end.slice(5,7))===month).map(e=>`<div><time>${md(e.date)}${e.end?`—${md(e.end)}`:''}</time><strong>${e.name}</strong></div>`).join('')}</section>`;}
function tableMarkup(rows,d=null){const sys=leagueSystems.find(s=>s.levels.some(l=>l.id===d?.id));return `<div class="league-table-wrap"><table class="league-table hub-table"><thead><tr><th>名次</th><th>球队</th><th>赛</th><th>胜</th><th>平</th><th>负</th><th>进 / 失</th><th>净胜</th><th>积分</th><th>席位</th></tr></thead><tbody>${rows.map((r,i)=>{const zone=!r.played?'':d?.relegation&&i>=d.teams-d.relegation?'降级区':d?.promotion&&i<2?'直接升级':d?.promotion&&i<6?'升级附加赛':d?.tier===1&&i<sys.globalSlots?(sys.id==='closed'?'季后赛 / 全球杯':'全球杯资格区'):!d&&i<2?'晋级区':'';return `<tr class="${zone==='降级区'?'zone-down':zone?'zone-up':''} ${r.id===clubFilter?'focused-team':''}"><td>${r.played?r.rank:'—'}</td><td>${badge(r.id)}${teamLink(r.id)}</td><td>${r.played}</td><td>${r.won}</td><td>${r.drawn}</td><td>${r.lost}</td><td>${r.gf} / ${r.ga}</td><td>${r.gd>0?'+':''}${r.gd}</td><td><strong>${r.points}</strong></td><td><small>${zone||'—'}</small></td></tr>`;}).join('')}</tbody></table></div>`;}
function tables(){const {competition}=context();if(competition==='global-cup')return `<p class="hub-caption">资格来源：${season.qualificationSource}</p>${season.groups.map(g=>`<section class="hub-match-group"><h3>${g.id} 组</h3>${tableMarkup(groupTable(season,g.id))}</section>`).join('')}<a class="football-link" href="${href('bracket')}">全球杯淘汰赛 ↗</a>`;if(competition!=='all'&&!getDivision(competition))return brackets();const divs=leagueSystems.flatMap(s=>s.levels).filter(d=>competition==='all'?clubFilter==='all'||season.members[d.id].includes(clubFilter):d.id===competition);return divs.map(d=>`<section class="hub-match-group"><h3>${d.name}<a href="${href('schedule',d.id)}">赛程 ↗</a></h3>${tableMarkup(tableFor(season,d.id),d)}<p class="hub-caption">${d.promotion?'前二直接升级 · 第 3—6 名参加升级附加赛 · ':''}${d.relegation?`末 ${d.relegation} 名降级 · `:''}积分 → 净胜球 → 进球数 → 相互战绩 → 公平竞赛 → 抽签</p></section>`).join('');}
function brackets(){const {competition}=context();const available=competitions.filter(c=>c.kind!=='league');let id=competition==='all'?bracketFilter:getDivision(competition)?available.find(c=>c.id===`${competition}-playoffs`)?.id||available.find(c=>c.system===competitions.find(c=>c.id===competition).system)?.id:competition;id||='closed-playoffs';const fs=season.fixtures.filter(m=>m.competition===id&&m.kind!=='group'),rounds=[...new Set(fs.map(m=>m.round))];return `<div class="hub-bracket-toolbar"><label>淘汰赛签表<select aria-label="淘汰赛签表" data-bracket>${options(available.map(c=>[c.id,c.name]),id)}</select></label><span>${id==='global-cup'?'单场 · 全部中立场':id==='closed-playoffs'?'单场 · 八强/半决赛高排名主场 · 决赛中立场':id.endsWith('-playoffs')?'单场 · 高排名球队主场':'单场 · 决赛中立场'}</span></div>${id==='global-cup'?`<p class="hub-caption">资格来源：${season.qualificationSource} · <a href="${href('table','global-cup')}">小组积分榜 ↗</a></p>`:''}<div class="hub-bracket">${rounds.map(round=>`<section><h3>${titleFor(fs.find(m=>m.round===round))}<small>${md(fs.find(m=>m.round===round).date)}</small></h3><div class="bracket-round">${fs.filter(m=>m.round===round).map(m=>{const {home,away}=fixtureSides(season,m);return `<button class="bracket-match ${m.bye?'bye':''}" data-report="${esc(m.id)}"><div class="${home&&m.winner===home?'winner':''}"><span>${esc(home?clubName(home):participant(m.home))}</span><b>${m.score?.[0]??'—'}</b></div><div class="${away&&m.winner===away?'winner':''}"><span>${esc(away?clubName(away):participant(m.away))}</span><b>${m.score?.[1]??'—'}</b></div><small>${m.bye?'轮空':m.shootout?`点球 ${m.shootout.score.join(':')}`:m.neutral?'中立场':m.kind==='playoff'?'高排名主场':'主 / 客'}</small></button>`;}).join('')}</div></section>`).join('')}</div>`;}
function summary(){const s=season.summary,{competition}=context(),matchesClub=id=>clubFilter==='all'||id===clubFilter;if(!s)return `<section class="hub-empty"><h2>赛季尚未结算</h2><p>12 月 1 日确认冠军、升降级及下一赛季资格。</p><p>${pendingMatches(season).length.toLocaleString()} 场待赛</p><a class="football-link" href="${href('bracket')}">查看附加赛签表 ↗</a></section>`;return `<div class="hub-summary"><section><h2>升降级 · ${season.year+1} 赛季</h2>${s.movements.filter(m=>matchesClub(m.id)&&(competition==='all'||m.from===competition||m.to===competition||competition===`${m.from}-playoffs`)).map(m=>`<div class="movement"><b class="${m.kind}">${m.kind==='up'?'↑ 升级':'↓ 降级'}</b>${teamLink(m.id)}<span>${competitionName(m.from)} → ${competitionName(m.to)}</span></div>`).join('')}</section><section><h2>赛季冠军</h2>${s.champions.filter(c=>matchesClub(c.id)&&(competition==='all'||c.competition===competition)).map(c=>`<div class="movement"><span>${competitionName(c.competition)}</span>${teamLink(c.id)}</div>`).join('')}<h2>${season.year+1} 全球冠军杯资格</h2>${s.qualifiers.filter(c=>matchesClub(c.id)&&(competition==='all'||competition==='global-cup'||c.system===competition)).map(c=>`<div class="movement">${teamLink(c.id)}<span>${competitionName(c.system)} · 第 ${c.rank} 名</span></div>`).join('')}</section></div>`;}
function draw(){if(!root||!season)return;const tab=context().tab;root.innerHTML=`${header()}${filters()}${tab==='calendar'?calendar():tab==='table'?tables():tab==='bracket'?brackets():tab==='summary'?summary():schedule()}<dialog class="hub-report" aria-label="比赛详情"><div id="hub-report-content"></div></dialog>`;const date=document.querySelector('.topbar .date');if(date)date.innerHTML=`<span>殖民历</span> ${peekSeason().year} <span>年 ${md(peekSeason().date)}</span>`;}
function report(id){const m=season.fixtures.find(m=>m.id===id);if(!m)return;const {home,away}=fixtureSides(season,m),dialog=root.querySelector('dialog'),data=m.report;dialog.querySelector('#hub-report-content').innerHTML=`<button data-close class="report-close" aria-label="关闭比赛详情">✕</button><p>${competitionName(m.competition)} · ${titleFor(m)}</p><div class="report-score"><div>${badge(home)}${teamLink(home)}</div><strong>${m.score?m.score.join(' : '):'VS'}</strong><div>${badge(away)}${teamLink(away)}</div></div><p>${md(m.date)} · ${m.time} · ${m.bye?'轮空':m.score?'已结束':'未开赛'}${m.neutral?' · 中立场':''}${m.shootout?` · 点球 ${m.shootout.score.join(' : ')}`:''}</p>${data?`<div class="report-stats">${[['shots','射门'],['onTarget','射正'],['xG','预期进球'],['corners','角球'],['fouls','犯规'],['yellow','黄牌'],['red','红牌']].map(([key,label])=>`<div><b>${key==='xG'?data.stats[0][key].toFixed(2):data.stats[0][key]}</b><span>${label}</span><b>${key==='xG'?data.stats[1][key].toFixed(2):data.stats[1][key]}</b></div>`).join('')}</div><h3>关键事件</h3>${data.events.map(e=>{const t=footballTeams.find(t=>t.id===[home,away][e.side]),p=registeredPlayer(season,e.player)||t?.roster.find(p=>p.id===e.player);return `<div class="report-event"><time>${e.minute}′</time><a href="#squad/${t?.id}/${p?.id}">${esc(p?.name||'球员')}</a><span>${e.type==='shot'?'进球':e.type==='red'?'红牌':`伤退 · ${e.days} 天`}</span></div>`;}).join('')||'<p>无进球、红牌或伤退</p>'}`:`<p>${m.bye?'本轮自动晋级':home&&away?'等待比赛日':'前序赛事结束后确定对阵'}</p>`}`;dialog.showModal();}
export function renderHub(){return '<section class="football-page season-hub" id="season-hub"><p role="status">正在读取赛季…</p></section>';}
export function disposeHub(){running=false;generation++;cleanup();root=null;}
export async function mountHub(){root=document.querySelector('#season-hub');const token=++generation;try{const current=await loadSeason();years=await archivedYears();if(token!==generation)return;season=viewYear&&viewYear!==current.year?await readSeason(viewYear):current;if(token!==generation)return;draw();}catch(error){if(token===generation&&root)root.innerHTML=`<h1>比赛中心</h1><p role="alert">${esc(error.message)}</p><button onclick="location.reload()">重新读取</button>`;return;}
 const click=async ev=>{const b=ev.target.closest('button');if(!b)return;
  if(b.hasAttribute('data-close')){root.querySelector('dialog').close();return;}
  if(b.dataset.report){report(b.dataset.report);return;}
  if(b.dataset.month){month=Number(b.dataset.month);selectedDate=null;draw();return;}
  if(b.dataset.day){selectedDate=b.dataset.day;draw();return;}
  if(b.dataset.calendarMonth){month=Number(b.dataset.calendarMonth);draw();return;}
  if(b.dataset.calendarDay){selectedDate=b.dataset.calendarDay;month=Number(selectedDate.slice(5,7));location.hash=href('schedule');return;}
  if(b.dataset.hub==='pause'){running=false;progress='正在暂停…';draw();return;}
  if(!b.dataset.hub||running)return;
  let target=b.dataset.hub==='until'?root.querySelector('[data-until]').value:nextDate(peekSeason());
  if(b.dataset.hub!=='new'&&(!target||target<peekSeason().date||target>dateOf(peekSeason().year,12,31))){notice='请选择本赛季内的未来日期';draw();return;}
  running=true;notice='';progress='正在推进赛历…';draw();
  try{if(b.dataset.hub==='new'){season=await newSeason();viewYear=null;month=3;selectedDate=null;years=await archivedYears();}else{while(running&&generation===token&&(peekSeason().date<target||pendingMatches(peekSeason()).some(m=>m.date===target))){const next=nextDate(peekSeason()),date=next&&next<target?next:target;season=await advanceDay(date,{shouldStop:()=>!running||generation!==token,onProgress:(n,total)=>{progress=`${md(date)} · ${n} / ${total} 场`;const status=root?.querySelector('.hub-status');if(status)status.textContent=progress;}});if(generation===token){month=Number(season.date.slice(5,7));selectedDate=season.date;draw();}if(readyManagedFixture(season)||season.activeMatch)break;await new Promise(r=>setTimeout(r,0));}}notice=readyManagedFixture(peekSeason())?'已到本队比赛日，请前往经理首页执教':'已保存';}catch(error){notice=error.message;season=peekSeason();}finally{running=false;progress='';if(generation===token)draw();}
 };
 const change=async ev=>{const el=ev.target;if(el.hasAttribute('data-competition')){clubFilter='all';selectedDate=null;location.hash=href(context().tab,el.value);}else if(el.hasAttribute('data-club')){clubFilter=el.value;selectedDate=null;draw();}else if(el.hasAttribute('data-year')){try{viewYear=Number(el.value);season=await readSeason(viewYear);if(generation===token){selectedDate=null;draw();}}catch(e){notice=e.message;draw();}}else if(el.hasAttribute('data-bracket')){bracketFilter=el.value;location.hash=href('bracket',el.value);}};
 root.addEventListener('click',click);root.addEventListener('change',change);const mounted=root;cleanup=()=>{mounted.removeEventListener('click',click);mounted.removeEventListener('change',change);};
}
