import {clubs} from '../world.js';
import {POSITIONS,rating} from '../football/players.js';
import {clubPlayers,populationPlayers,populationPlayer} from './population.js';
import {seasonPlayer} from './runtime.js';
import {loadSeason,peekSeason,saveMarketAction} from './store.js';
import {ensureEconomy,wageBill,availableBudget,isTransferWindow,transferQuote,renewalQuote,releaseQuote,saleOffers} from './market.js';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>`${Math.round(n).toLocaleString('zh-CN')} 星元`,name=id=>clubs.find(c=>c.id===id)?.name||'自由球员';
const select=(label,options,value,attribute)=>`<label>${label}<select ${attribute}>${options.map(([id,text])=>`<option value="${esc(id)}" ${id===value?'selected':''}>${esc(text)}</option>`).join('')}</select></label>`;
let root=null,generation=0,cleanup=()=>{},busy=false,section='recruit',position='all',source='all',search='',selected=null,years=3,notice='';
const types={transfer:'转会',renewal:'续约',expiry:'合同到期',release:'解约',professional:'职业合同'};
function playerLink(p){return `<a href="#squad/${esc(p.club||p.lastClub)}/${esc(p.id)}">${esc(p.name)}</a>`;}
function preview(s,p){
 if(!p)return '<section class="manager-panel"><h2>合同详情</h2><p>选择球员查看条款</p></section>';
 const own=p.club===s.manager.clubId,c=s.economy.contracts[p.id],view=seasonPlayer(s,p.id);let q=null,error='';
 try{q=own?renewalQuote(s,p.id,years):transferQuote(s,p.id,s.manager.clubId,years);}catch(e){error=e.message;}
 let release=null,sales=[];if(own){try{release=releaseQuote(s,p.id);}catch{}sales=saleOffers(s,p.id);}
 return `<section class="manager-panel market-detail"><small>${POSITIONS[p.position]} · ${view.age} 岁 · ${rating(view)}</small><h2>${esc(p.name)}</h2><p>${esc(name(p.club))}${p.unit==='youth'?' · 青年队':''}</p>${playerLink(p)}${c?`<p>当前合同至 ${c.end}<br>周薪 ${money(c.weeklyWage)}</p>`:''}${select('合同期限',[[1,'1 年'],[2,'2 年'],[3,'3 年']],years,'data-market-years')}
 ${q?`<dl><div><dt>合同至</dt><dd>${q.end}</dd></div>${!own?`<div><dt>转会费</dt><dd>${money(q.fee)}</dd></div>`:''}<div><dt>周薪</dt><dd>${money(q.weeklyWage)}</dd></div><div><dt>签字费</dt><dd>${money(q.bonus)}</dd></div></dl>`:`<p>${esc(error)}</p>`}<button class="football-primary" data-market-action="${own?'renew':'sign'}" data-id="${esc(p.id)}" ${busy||!q?'disabled':''}>${own?'按以上条款续约':'按以上条款签约'}</button>
 ${own?`<details><summary>出售或解约</summary>${sales.length?sales.map(q=>`<div class="market-offer"><p>${esc(name(q.to))} · ${money(q.fee)}</p><button data-market-action="sell" data-id="${esc(p.id)}" data-buyer="${esc(q.to)}" ${busy?'disabled':''}>接受报价</button></div>`).join(''):'<p>暂无可成交报价</p>'}${release?`<p>解约补偿 ${money(release.compensation)}</p><button data-market-action="release" data-id="${esc(p.id)}" ${busy?'disabled':''}>支付补偿并解约</button>`:'<p>当前阵容或资金不允许解约</p>'}</details>`:''}</section>`;
}
function draw(){if(!root)return;const s=peekSeason();if(!s.manager){root.innerHTML='<h1>转会与合同</h1><p>接手俱乐部后可管理合同</p><a href="#manager">选择球队 →</a>';return;}const e=ensureEconomy(s),own=s.manager.clubId,a=e.accounts[own];
 let players=section==='contracts'?clubPlayers(s,own,{unit:'all'}):populationPlayers(s).filter(p=>p.club!==own&&['senior','free'].includes(p.unit));
 if(section==='recruit'&&source==='available')players=players.filter(p=>{try{transferQuote(s,p.id,own,years);return true;}catch{return false;}});
 players=players.filter(p=>(position==='all'||p.position===position)&&(section==='contracts'||source!=='free'||!p.club)&&(!search||`${p.name} ${p.originalName||''}`.toLowerCase().includes(search.toLowerCase()))).map(p=>seasonPlayer(s,p.id)).sort((a,b)=>rating(b)-rating(a)||a.id.localeCompare(b.id));
 const selectedPlayer=selected&&populationPlayer(s,selected),shown=players.slice(0,60),moves=e.moves.filter(m=>m.from===own||m.to===own||m.club===own).slice(-80).reverse();
 root.innerHTML=`<header class="football-title"><div><small>${s.date} · ${isTransferWindow(s)?'注册窗口开放':'注册窗口关闭'}</small><h1>转会与合同</h1></div><a class="football-link" href="#manager">经理首页 ↗</a></header><div class="manager-stats manager-season-stats"><div><strong>${Math.round(a.cash).toLocaleString('zh-CN')}</strong><span>现金 · 星元</span></div><div><strong>${Math.round(availableBudget(s,own)).toLocaleString('zh-CN')}</strong><span>可用引援资金 · 星元</span></div><div><strong>${wageBill(s,own).toLocaleString('zh-CN')}</strong><span>当前周薪 · 星元</span></div><div><strong>${a.wageLimit.toLocaleString('zh-CN')}</strong><span>周薪上限 · 星元</span></div></div><nav class="market-tabs" aria-label="合同页面">${[['recruit','引援'],['contracts','本队合同'],['history','交易记录']].map(([id,label])=>`<button data-market-section="${id}" aria-pressed="${id===section}">${label}</button>`).join('')}</nav><p role="status" id="market-notice">${esc(notice||'资金已预留本赛季剩余工资')}</p>
 ${section==='history'?`<section class="manager-panel"><h2>交易记录</h2>${moves.length?`<ul class="market-history">${moves.map(m=>{const p=populationPlayer(s,m.player);return `<li><time>${m.date}</time><span>${types[m.type]||m.type} · ${p?playerLink(p):esc(m.player)}<small>${esc(name(m.from||m.club))}${m.to?` → ${esc(name(m.to))}`:''}</small></span><strong>${m.fee!=null?money(m.fee):m.weeklyWage?`${money(m.weeklyWage)} / 周`:''}</strong></li>`;}).join('')}</ul>`:'<p>暂无交易</p>'}<details><summary>本赛季账本</summary><dl>${[['funding','运营收入'],['transferIn','出售收入'],['transferOut','引援支出'],['bonuses','签字费'],['wages','已付工资'],['severance','解约补偿']].map(([key,label])=>`<div><dt>${label}</dt><dd>${money(a.season[key])}</dd></div>`).join('')}</dl></details></section>`:`<div class="market-layout"><section class="manager-panel"><div class="market-filters">${select('位置',[['all','全部位置'],...Object.entries(POSITIONS)],position,'data-market-position')}${section==='recruit'?select('范围',[['all','全部球员'],['available','可签约'],['free','自由球员']],source,'data-market-source'):''}<label>姓名<input data-market-search value="${esc(search)}" placeholder="输入姓名后回车"></label></div><p>${players.length} 名球员${players.length>60?' · 显示前 60 名':''}</p><div class="market-table"><table><thead><tr><th>球员</th><th>位置</th><th>年龄</th><th>能力</th><th>${section==='contracts'?'合同到期':'俱乐部'}</th></tr></thead><tbody>${shown.map(p=>`<tr class="${p.id===selected?'own':''}"><td><button data-market-player="${esc(p.id)}">${esc(p.name)}</button></td><td>${p.position}</td><td>${p.age}</td><td>${rating(p)}</td><td>${section==='contracts'?e.contracts[p.id]?.end||'—':esc(name(p.club))}</td></tr>`).join('')}</tbody></table>${!shown.length?'<p>无符合条件的球员</p>':''}</div></section>${preview(s,selectedPlayer)}</div>`}`;
}
export function renderMarket(){return '<section class="football-page market-page" id="market-root"><p>正在读取合同…</p></section>';}
export function disposeMarket(){generation++;cleanup();root=null;busy=false;}
export async function mountMarket(){root=document.querySelector('#market-root');const token=++generation;try{await loadSeason();if(token!==generation)return;draw();}catch(error){if(token===generation)root.innerHTML=`<p role="alert">${esc(error.message)}</p>`;return;}
 const click=async ev=>{const b=ev.target.closest('[data-market-section],[data-market-player],[data-market-action]');if(!b||busy)return;if(b.dataset.marketSection){section=b.dataset.marketSection;selected=null;notice='';draw();return;}if(b.dataset.marketPlayer){selected=b.dataset.marketPlayer;notice='';draw();root.querySelector('.market-detail')?.scrollIntoView({block:'start'});return;}const {marketAction:action,id,buyer}=b.dataset;busy=true;const revision=peekSeason().revision;notice='正在保存…';draw();try{await saveMarketAction({action,id,buyer,years:action==='sell'?3:years,revision});if(token===generation){notice='已保存';if(action==='release'||action==='sell')selected=null;}}catch(error){if(token===generation)notice=error.message;}finally{if(token===generation){busy=false;draw();}}};
 const change=ev=>{if(busy)return;const el=ev.target;if(el.hasAttribute('data-market-position'))position=el.value;else if(el.hasAttribute('data-market-source'))source=el.value;else if(el.hasAttribute('data-market-search'))search=el.value.trim();else if(el.hasAttribute('data-market-years'))years=Number(el.value);else return;draw();};const keydown=ev=>{if(ev.key==='Enter'&&ev.target.hasAttribute('data-market-search')){ev.preventDefault();change(ev);}};root.addEventListener('click',click);root.addEventListener('change',change);root.addEventListener('keydown',keydown);const mounted=root;cleanup=()=>{mounted.removeEventListener('click',click);mounted.removeEventListener('change',change);mounted.removeEventListener('keydown',keydown);};
}
