import {sortPlayers,sortControls,PLAYER_SORTS} from '../list-sort.js';
import {formatMoney,moneyData} from '../format.js';
import {clubIdentity,seniorTeams} from './team-directory.js';
import {salaryBreakdown} from './taxation.js';
import {clubs} from '../world.js';
import {POSITIONS,rating} from '../football/players.js';
import {clubPlayers,populationPlayers,populationPlayer} from './population.js';
import {seasonPlayer} from './runtime.js';
import {loadSeason,peekSeason,saveMarketAction} from './store.js';
import {ensureEconomy,askingPrice,wageBill,availableBudget,isTransferWindow,transferQuote,renewalQuote,releaseQuote,saleOffers} from './market.js';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>formatMoney(n,{currency:true}),name=id=>clubIdentity(id)?.name||'自由球员';
const select=(label,options,value,attribute)=>`<label>${label}<select ${attribute}>${options.map(([id,text])=>`<option value="${esc(id)}" ${id===value?'selected':''}>${esc(text)}</option>`).join('')}</select></label>`;
let root=null,generation=0,cleanup=()=>{},busy=false,section='recruit',position='all',source='all',search='',selected=null,years=3,notice='',sortKey='ability',sortDirection='desc',page=0;
const types={transfer:'转会',renewal:'续约',expiry:'合同到期',release:'解约',professional:'职业合同'};
function playerLink(p){return `<a href="#squad/${esc(p.club||p.lastClub)}/${esc(p.id)}">${esc(p.name)}</a>`;}
function preview(s,p){
 if(!p)return '<section class="manager-panel"><h2>合同详情</h2><p>选择球员查看条款</p></section>';
 const own=p.club===s.manager.clubId,c=s.economy.contracts[p.id],view=seasonPlayer(s,p.id);let q=null,error='';
 try{q=own?renewalQuote(s,p.id,years):transferQuote(s,p.id,s.manager.clubId,years);}catch(e){error=e.message;}
 let release=null,sales=[];if(own){try{release=releaseQuote(s,p.id);}catch{}sales=saleOffers(s,p.id);}
 return `<section class="manager-panel market-detail"><small>${POSITIONS[p.position]} · ${view.age} 岁 · ${rating(view)}</small><h2>${esc(p.name)}</h2><p>${esc(name(p.club))}${p.unit==='youth'?' · 青年队':''}</p>${playerLink(p)}${c?`<p>当前合同至 ${c.end}<br>税前周薪 ${money(c.weeklyWage)}</p>`:''}${select('合同期限',[[1,'1 年'],[2,'2 年'],[3,'3 年']],years,'data-market-years')}
 ${q?`<dl><div><dt>合同至</dt><dd>${q.end}</dd></div>${!own?`<div><dt>转会费</dt><dd>${money(q.fee)}</dd></div>${q.transferTax!=null?`<div><dt>卖方转会税</dt><dd>${money(q.transferTax)}</dd></div><div><dt>卖方实收</dt><dd>${money(q.sellerNet)}</dd></div>`:''}`:''}<div><dt>税前周薪</dt><dd>${money(q.weeklyWage)}</dd></div>${s.economy.taxVersion===1?`<div><dt>税后周薪估算</dt><dd>${money(salaryBreakdown(s,q.weeklyWage).netWeekly)}</dd></div>`:''}<div><dt>签字费</dt><dd>${money(q.bonus)}</dd></div>${s.economy.taxVersion===1?'<div><dt>税后估算口径</dt><dd>仅工资全年收入，不含奖金</dd></div>':''}${q.bidding?`<div><dt>竞价球队</dt><dd>${q.bidding.bidders.length} 家</dd></div><div><dt>竞价溢价</dt><dd>${Math.round((q.bidding.factor-1)*100)}%</dd></div>`:''}${q.outsideOffer?`<div><dt>外部报价周薪</dt><dd>${money(q.outsideOffer.weeklyWage)}</dd></div>`:''}</dl>`:`<p>${esc(error)}</p>`}<button class="football-primary" data-market-action="${own?'renew':'sign'}" data-id="${esc(p.id)}" ${busy||!q?'disabled':''}>${own?'按以上条款续约':'按以上条款签约'}</button>
 ${own?`<details><summary>出售或解约</summary>${sales.length?sales.map(q=>`<div class="market-offer"><p>${esc(name(q.to))} · ${money(q.fee)}${q.transferTax!=null?`<br>转会税 ${money(q.transferTax)} · 实收 ${money(q.sellerNet)}`:''}</p><button data-market-action="sell" data-id="${esc(p.id)}" data-buyer="${esc(q.to)}" ${busy?'disabled':''}>接受报价</button></div>`).join(''):'<p>暂无可成交报价</p>'}${release?`<p>解约补偿 ${money(release.compensation)}</p><button data-market-action="release" data-id="${esc(p.id)}" ${busy?'disabled':''}>支付补偿并解约</button>`:'<p>当前阵容或资金不允许解约</p>'}</details>`:''}</section>`;
}
function draw(){if(!root)return;const s=peekSeason();if(!s.manager){root.innerHTML='<h1>转会与合同</h1><p>接手俱乐部后可管理合同</p><a href="#manager">选择球队 →</a>';return;}const e=ensureEconomy(s),own=s.manager.clubId,a=e.accounts[own];
 let players=section==='contracts'?clubPlayers(s,own,{unit:'all'}):populationPlayers(s).filter(p=>p.club!==own&&['senior','free'].includes(p.unit));
 if(section==='recruit'&&source==='available')players=players.filter(p=>{try{transferQuote(s,p.id,own,years);return true;}catch{return false;}});
 players=players.filter(p=>(position==='all'||p.position===position)&&(section==='contracts'||source!=='free'||!p.club)&&(!search||`${p.name} ${p.originalName||''}`.toLowerCase().includes(search.toLowerCase()))).map(p=>seasonPlayer(s,p.id));
 players=sortPlayers(players,{key:sortKey,direction:sortDirection,wage:p=>e.contracts[p.id]?.weeklyWage,value:p=>askingPrice(s,p)});
 const maxPage=Math.max(0,Math.ceil(players.length/60)-1);page=Math.min(page,maxPage);
 const selectedPlayer=selected&&populationPlayer(s,selected),shown=players.slice(page*60,(page+1)*60),moves=e.moves.filter(m=>m.from===own||m.to===own||m.club===own).slice().reverse();
 root.innerHTML=`<header class="football-title"><div><small>${s.date} · ${isTransferWindow(s)?'注册窗口开放':'注册窗口关闭'}</small><h1>转会与合同</h1></div><a class="football-link" href="#manager">经理首页 ↗</a></header><div class="manager-stats manager-season-stats"><div><strong>${formatMoney(a.cash)}</strong><span>现金 · 星元</span></div><div><strong>${formatMoney(availableBudget(s,own))}</strong><span>可用引援资金 · 星元</span></div><div><strong>${formatMoney(wageBill(s,own))}</strong><span>当前周薪 · 星元</span></div><div><strong>${formatMoney(a.wageLimit)}</strong><span>${e.financeVersion?'工资软线':'周薪上限'} · 星元</span></div></div><nav class="market-tabs" aria-label="合同页面">${[['recruit','引援'],['contracts','本队合同'],['history','交易记录']].map(([id,label])=>`<button data-market-section="${id}" aria-pressed="${id===section}">${label}</button>`).join('')}</nav><p role="status" id="market-notice">${esc(notice||(e.financeVersion?'资金已预留工资与预计经营缺口':'资金已预留本赛季剩余工资'))}</p>
 ${section==='history'?`<section class="manager-panel"><h2>交易记录</h2>${moves.length?`<div class="market-table"><table><thead><tr><th>日期</th><th>交易</th><th>球员</th><th>原俱乐部</th><th>新俱乐部</th><th>转会费</th><th>周薪</th></tr></thead><tbody>${moves.map(m=>{const p=populationPlayer(s,m.player);return `<tr><td>${m.date}</td><td>${types[m.type]||m.type}</td><td>${p?playerLink(p):esc(m.player)}</td><td>${esc(name(m.from||m.club))}</td><td>${m.to?esc(name(m.to)):'—'}</td><td data-sort-value="${m.fee??''}">${money(m.fee)}</td><td data-sort-value="${m.weeklyWage??''}">${money(m.weeklyWage)}</td></tr>`;}).join('')}</tbody></table></div>`:'<p>暂无交易</p>'}<details><summary>本赛季账本</summary><dl>${[['funding','运营收入'],['transferIn','出售收入'],['transferOut','引援支出'],['bonuses','签字费'],['wages','已付工资'],['severance','解约补偿'],['transferTax','转会交易税']].map(([key,label])=>`<div><dt>${label}</dt><dd>${money(a.season[key]||0)}</dd></div>`).join('')}</dl></details></section>`:`<div class="market-layout"><section class="manager-panel"><div class="market-filters">${select('位置',[['all','全部位置'],...Object.entries(POSITIONS)],position,'data-market-position')}${section==='recruit'?select('范围',[['all','全部球员'],['available','可签约'],['free','自由球员']],source,'data-market-source'):''}${sortControls('market',sortKey,sortDirection,PLAYER_SORTS.filter(([k])=>['name','position','age','ability','wage','value'].includes(k)))}<label>姓名<input data-market-search value="${esc(search)}" placeholder="输入姓名后回车"></label></div><p>${players.length} 名球员 · 第 ${page+1} / ${maxPage+1} 页</p><div class="market-table"><table data-model-sort><thead><tr>${[['name','球员'],['position','位置'],['age','年龄'],['ability','能力 / 200'],['wage','周薪'],['value','参考身价']].map(([key,label])=>`<th aria-sort="${sortKey===key?(sortDirection==='asc'?'ascending':'descending'):'none'}"><button class="table-sort-button" aria-label="按${label}排序" data-market-order="${key}">${label}</button></th>`).join('')}<th>${section==='contracts'?'合同到期':'俱乐部'}</th></tr></thead><tbody>${shown.map(p=>`<tr class="${p.id===selected?'own':''}"><td><button data-market-player="${esc(p.id)}">${esc(p.name)}</button></td><td>${POSITIONS[p.position]}</td><td>${p.age}</td><td>${rating(p)}</td><td>${money(e.contracts[p.id]?.weeklyWage)}</td><td>${money(askingPrice(s,p))}</td><td>${section==='contracts'?e.contracts[p.id]?.end||'—':esc(name(p.club))}</td></tr>`).join('')}</tbody></table></div><div class="market-pagination"><button data-market-page="${page-1}" ${page===0?'disabled':''}>上一页</button><span>${page+1} / ${maxPage+1}</span><button data-market-page="${page+1}" ${page===maxPage?'disabled':''}>下一页</button></div>${!shown.length?'<p>无符合条件的球员</p>':''}</section>${preview(s,selectedPlayer)}</div>`}`;
}
export function renderMarket(){return '<section class="football-page market-page" id="market-root"><p>正在读取合同…</p></section>';}
export function disposeMarket(){generation++;cleanup();root=null;busy=false;}
export async function mountMarket(){root=document.querySelector('#market-root');const token=++generation;try{await loadSeason();if(token!==generation)return;draw();}catch(error){if(token===generation)root.innerHTML=`<p role="alert">${esc(error.message)}</p>`;return;}
 const click=async ev=>{const b=ev.target.closest('[data-market-section],[data-market-player],[data-market-action],[data-market-order],[data-market-page]');if(!b||busy)return;if(b.hasAttribute('data-market-page')){page=Number(b.dataset.marketPage);draw();root.querySelector('.market-filters')?.scrollIntoView({block:'start'});return;}if(b.dataset.marketOrder){sortDirection=sortKey===b.dataset.marketOrder&&sortDirection==='desc'?'asc':'desc';sortKey=b.dataset.marketOrder;page=0;draw();return;}if(b.dataset.marketSection){page=0;section=b.dataset.marketSection;selected=null;notice='';draw();return;}if(b.dataset.marketPlayer){selected=b.dataset.marketPlayer;notice='';draw();root.querySelector('.market-detail')?.scrollIntoView({block:'start'});return;}const {marketAction:action,id,buyer}=b.dataset;busy=true;const revision=peekSeason().revision;notice='正在保存…';draw();try{await saveMarketAction({action,id,buyer,years:action==='sell'?3:years,revision});if(token===generation){notice='已保存';if(action==='release'||action==='sell')selected=null;}}catch(error){if(token===generation)notice=error.message;}finally{if(token===generation){busy=false;draw();}}};
 const change=ev=>{if(busy)return;const el=ev.target;if(el.hasAttribute('data-market-sort'))sortKey=el.value;else if(el.hasAttribute('data-market-direction'))sortDirection=el.value;else if(el.hasAttribute('data-market-position'))position=el.value;else if(el.hasAttribute('data-market-source'))source=el.value;else if(el.hasAttribute('data-market-search'))search=el.value.trim();else if(el.hasAttribute('data-market-years'))years=Number(el.value);else return;page=0;draw();};const keydown=ev=>{if(ev.key==='Enter'&&ev.target.hasAttribute('data-market-search')){ev.preventDefault();change(ev);}};root.addEventListener('click',click);root.addEventListener('change',change);root.addEventListener('keydown',keydown);const mounted=root;cleanup=()=>{mounted.removeEventListener('click',click);mounted.removeEventListener('change',change);mounted.removeEventListener('keydown',keydown);};
}
