import {formatMoney,moneyData} from '../format.js';
import {clubIdentity,seniorTeams} from './team-directory.js';
import {clubs} from '../world.js';
import {loadSeason,peekSeason,archivedYears,readSeason} from './store.js';
import {ensureEconomy,wageBill,availableBudget} from './market.js';
import {INCOME_LABELS,EXPENSE_LABELS,financeYear,financePolicy,annualTax} from './finance.js';
import {clubProfile} from './club-profiles.js';
import {historyRecords,historicalResults,championRanking,competitionName,MVP_RULE,seasonRecord} from './history.js';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const name=id=>clubIdentity(id)?.name||id;
const money=n=>moneyData(n??0);
const compactMoney=formatMoney;
const options=(rows,value)=>rows.map(([id,label])=>`<option value="${esc(id)}" ${String(id)===String(value)?'selected':''}>${esc(label)}</option>`).join('');
const table=(heads,rows)=>`<div class="manager-table-wrap"><table class="manager-table"><thead><tr>${heads.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map(v=>`<td>${v}</td>`).join('')}</tr>`).join('')}</tbody></table>${rows.length?'':'<p>暂无记录</p>'}</div>`;
let root,token=0,club=null,opponent='',competition='all',year='all',records=[],shownCompetitions=[];
export function financeContent(s,id){
 const e=ensureEconomy(s),a=e.accounts[id],current=financeYear(s,id),years=[...a.history,current],policy=financePolicy(s,id);
 return `<header class="football-title"><div><small>${s.date} · ${esc(clubProfile(id).owner)}</small><h1>${esc(name(id))} · 财政</h1></div><a href="#market">转会与合同 ↗</a></header>
 <label>俱乐部<select data-record-club>${options(seniorTeams(s).map(c=>[c.id,c.name]),id)}</select></label>
 <div class="manager-stats manager-season-stats">${[[a.cash,'现金'],[availableBudget(s,id),'可用引援资金'],[current.operatingRevenue,'本年经营收入'],[current.expenseTotal,'本年总支出']].map(([n,label])=>`<div><strong>${compactMoney(n)}</strong><span>${label} · 星元</span></div>`).join('')}</div>
 ${a.business?`<section class="manager-panel records-block"><h2>年度经营规模</h2><div class="manager-stats manager-season-stats">${[[a.operatingRevenueBudget,'预计经营收入'],[wageBill(s,id)*52,'当前年化球员工资'],[a.transferBudget,'年度引援预算']].map(([n,label])=>`<div><strong>${compactMoney(n)}</strong><span>${label} · 星元</span></div>`).join('')}</div><p>经营收入不含转会出售、股东注资和降级补助；实际收支按比赛与日历计入。</p><p>球场 ${a.business.stadiumCapacity.toLocaleString('zh-CN')} 席 · 预计上座率 ${Math.round(a.business.attendance*100)}% · 每位观众平均消费 ${money(a.business.ticketYield)} 星元 · 联赛主场 ${a.business.homeGames} 场</p></section>`:''}
 ${a.cash<0?`<section class="manager-panel"><h2>资金缺口 ${money(-a.cash)} 星元</h2><p>可用引援资金为0，新增合同须满足现金预留。</p></section>`:''}<div class="manager-grid"><section class="manager-panel"><h2>本年收支</h2>${e.financeSince&&e.financeSince>`${String(e.year).padStart(4,'0')}-01-01`?`<p>收入分类自 ${e.financeSince} 起记录</p>`:''}${table(['收入','星元'],[...Object.entries(INCOME_LABELS).map(([k,label])=>[label,money(a.income?.[k])]),['转会收入',money(a.season.transferIn)],...(a.seasonUnclassifiedFunding?[['迁移前未分类收入',money(a.seasonUnclassifiedFunding)]]:[])])}${table(['支出','星元'],Object.entries(EXPENSE_LABELS).map(([k,label])=>[label,money(a.season[k])]))}<p>本年净收支 ${money(current.net)} 星元</p>${a.withholding?`<h2>球员收入分配</h2>${table(['项目','星元'],[['税前工资、奖金与补偿',money(a.withholding.season.gross)],['代扣个人所得税',money(a.withholding.season.incomeTax)],['球员实得',money(a.withholding.season.net)]])}<p>代扣个税已包含在税前支出中。</p>`:''}</section>
 <section class="manager-panel"><h2>${esc(policy.name)}</h2><p>当前周薪 ${money(wageBill(s,id))} 星元<br>工资软线 ${money(a.wageLimit)} 星元 / 周<br>按当前工资预计全年超额税 ${money(e.financeVersion?annualTax(a,wageBill(s,id)):0)} 星元</p><p>软线为预计经营收入的 ${Math.round(policy.wageRatio*100)}%。超额部分税率 ${Math.round(policy.taxRate*100)}%，超过软线 115% 的部分再加征同等税率。</p><p>滚动三年允许亏损：同期非股东、非转会收入的 ${Math.round(policy.lossAllowance*100)}%。审查结果：${esc(a.review?.status||'未审查')}。</p><p>审查亏损 ${money(a.review?.loss)} / 允许 ${money(a.review?.allowance)} 星元</p><p>俱乐部预算最多容许工资达到软线的 135%；违规时收紧到软线。签约后预留至少八周工资，并覆盖本年及下一年预计资金缺口。</p><p>可用一线队不足18人时，本队17—20岁地方青训可临时征召，继续履行原合同；仍不足11人时可紧急征召满16岁青训；可用人数为7—10人时少人参赛。</p><p>降级后两年分别补助固定场外收入降幅的60%、30%，不增加工资软线和转会预算。</p><h2>年度经营预算</h2>${table(['项目','星元'],[...Object.entries(a.plan||{}).map(([k,n])=>[INCOME_LABELS[k],money(n)]),['预计比赛日收入',money(a.expectedMatchday)],['运营支出',money(a.operatingBudget)]])}</section></div>
 ${e.taxation?`<section class="manager-panel records-block"><h2>税收与联盟资金累计</h2>${table(['地区','转会税','个人所得税','联盟超额税'],Object.entries(e.taxation.regions).map(([region,r])=>[({metro:'大都会',lima:'利玛',liberlin:'利柏林',sichuan:'新四川'})[region],money(r.totals.transferTax),money(r.totals.incomeTax),money(r.totals.leagueLevy)]))}</section>`:''}<section class="manager-panel records-block"><h2>逐年账本</h2>${table(['年份','现金流入','税前工资','引援','出售','运营','超额税','转会税','代扣个税','净收支','期末现金'],years.map(r=>[r.year,money(r.incomeTotal??r.funding+r.transferIn),money(r.wages),money(r.transferOut),money(r.transferIn),money(r.operating),money(r.tax),money(r.transferTax),money(r.withholding?.incomeTax),money(r.net??r.funding+r.transferIn-r.wages-r.transferOut-r.bonuses-r.severance),money(r.cash)]))}</section>`;
}
function competitionContent(c){return `${c.table?table(['名次','球队','场次','胜','平','负','进球','失球','积分'],c.table.map(r=>[r.rank,esc(name(r.id)),r.played,r.won,r.drawn,r.lost,r.gf,r.ga,r.points])):table(['球队','场次','胜','平','负'],c.teams.map(r=>[esc(name(r.id)),r.played,r.won,r.drawn,r.lost]))}${table(['射手前十','进球','助攻'],c.leaderboards.goals.map(p=>[esc(p.name),p.goals,p.assists]))}${table(['助攻前十','助攻'],c.leaderboards.assists.map(p=>[esc(p.name),p.assists]))}`; }
function draw(){
 if(!root)return;const s=peekSeason();club??=s.manager?.clubId||'sky';if(location.hash.startsWith('#finance')){root.innerHTML=financeContent(s,club);return;}
 const filtered=records.filter(r=>year==='all'||r.year===Number(year)),ids=[...new Set(records.flatMap(r=>r.competitions.map(c=>c.competition)))];
 const results=historicalResults(filtered,{club,opponent:opponent||undefined,competition}),top=historicalResults(filtered,{club,opponent:opponent||undefined,competition,topFlight:true});
 const titles=filtered.flatMap(r=>r.competitions.filter(c=>competition==='all'||c.competition===competition).map(c=>({year:r.year,...c}))),ranks=championRanking(filtered,competition);
 shownCompetitions=titles;
 root.innerHTML=`<header class="football-title"><div><small>${records.length?`${records[0].year}—${records.at(-1).year} 年`:'尚无已结算赛季'}</small><h1>历史记录</h1></div><a href="#manager">经理首页 ↗</a></header><div class="records-filters"><label>年份<select data-record-year>${options([['all','全部年份'],...records.map(r=>[r.year,r.year])],year)}</select></label><label>赛事<select data-record-competition>${options([['all','全部赛事'],...ids.map(id=>[id,competitionName(id)])],competition)}</select></label><label>球队<select data-record-club>${options(clubs.map(c=>[c.id,c.name]),club)}</select></label><label>交手对手<select data-record-opponent>${options([['','全部对手'],...clubs.filter(c=>c.id!==club).map(c=>[c.id,c.name])],opponent)}</select></label></div>
 <section class="manager-panel records-block"><h2>${esc(name(club))}${opponent?` 对 ${esc(name(opponent))}`:''}</h2><p>胜平负按常规时间及加时后的比分；点球胜负单列。顶级联赛仅含常规联赛。</p>${table(['范围','场次','胜','平','负','进球','失球','点球胜','点球负'],[['所选赛事',results],['顶级联赛',top]].map(([label,r])=>[label,r.played,r.won,r.drawn,r.lost,r.gf,r.ga,r.shootoutWon,r.shootoutLost]))}<details><summary>逐场交手记录 · ${results.matches.length}</summary>${table(['日期','赛事','主队','比分','客队','点球'],results.matches.map(m=>[m.date,esc(competitionName(m.competition)),esc(name(m.home)),m.score.join(' : '),esc(name(m.away)),m.shootout?.score.join(' : ')||'—']))}</details></section>
 <section class="manager-panel records-block"><h2>冠军排名</h2><p>按年份、赛事筛选；不随球队筛选。升级附加赛优胜不计入冠军总数。</p>${table(['排名','球队','冠军次数'],ranks.map((r,i)=>[i+1,esc(name(r.id)),r.titles]))}</section>
 <section class="manager-panel records-block"><h2>历届冠军与赛事 MVP</h2><details><summary>MVP 口径</summary><p>${MVP_RULE}</p></details>${table(['年份','赛事','冠军 / 优胜者','MVP','贡献分','进球 / 助攻'],titles.map(c=>[c.year,esc(competitionName(c.competition,c.name)),esc(name(c.champion)),c.completeStats?esc(c.mvp?.name||'暂无达标球员'):'旧档数据不完整',c.completeStats&&c.mvp?c.mvp.contribution:'—',c.completeStats&&c.mvp?`${c.mvp.goals} / ${c.mvp.assists}`:'—']))}</section>
 <section class="manager-panel records-block"><h2>赛事数据</h2>${titles.map((c,i)=>`<details data-record-event="${i}"><summary>${c.year} · ${esc(competitionName(c.competition,c.name))} · ${c.matches} 场 / ${c.goals} 球</summary><div></div></details>`).join('')||'<p>赛季结算后显示</p>'}</section>`;
}
export function renderRecords(){return '<section class="football-page" id="records-root"><p role="status">正在读取记录…</p></section>';}
export function disposeRecords(){token++;root=null;}
export async function mountRecords(){const current=++token;root=document.querySelector('#records-root');try{const s=await loadSeason();records=historyRecords(s);if(!location.hash.startsWith('#finance')){for(const y of await archivedYears())if(y!==s.year&&!records.some(r=>r.year===y)){const old=await readSeason(y);if(old.summary)records.push(seasonRecord(old));}records.sort((a,b)=>a.year-b.year);}if(current!==token)return;draw();root.addEventListener('toggle',ev=>{const d=ev.target;if(d.open&&d.hasAttribute('data-record-event')&&!d.dataset.loaded){d.querySelector('div').innerHTML=competitionContent(shownCompetitions[Number(d.dataset.recordEvent)]);d.dataset.loaded='true';}},true);root.addEventListener('change',ev=>{const el=ev.target;if(el.hasAttribute('data-record-club')){club=el.value;if(opponent===club)opponent='';}else if(el.hasAttribute('data-record-opponent'))opponent=el.value;else if(el.hasAttribute('data-record-year'))year=el.value;else if(el.hasAttribute('data-record-competition'))competition=el.value;else return;draw();});}catch(error){if(current===token)root.innerHTML=`<p role="alert">${esc(error.message)}</p>`;}}
