import {leagues,clubs,YEAR,regions,provinces,cities} from '../world.js';
import {loadSeason,peekSeason} from './store.js';
import {GLOBAL_CUP,METRO_CHAMPIONS,isMetroLeague} from './catalog.js';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const byId=id=>clubs.find(c=>c.id===id),link=(url,label,cls='')=>`<a class="${cls}" href="#${url}">${label}</a>`;
let root=null,generation=0;
function context(){const [,systemId='all',tier='1',tab='overview',r='1']=location.hash.split('/');const system=leagues.find(s=>s.id===systemId);const division=system?.levels.find(d=>d.tier===Number(tier))||system?.levels[0];return {systemId,system,division,tab,r:Math.max(1,Number(r)||1)};}
const fact=(label,value)=>`<div><small>${label}</small><strong>${value}</strong></div>`;
const panel=(title,body)=>`<section class="league-panel"><h2>${title}</h2>${body}</section>`;
const list=rows=>`<dl class="league-rules">${rows.map(([k,v])=>`<div><dt>${k}</dt><dd>${v}</dd></div>`).join('')}</dl>`;
function overview(){return `<div class="football-title"><div><small>${peekSeason()?.year||YEAR} 赛季</small><h1>赛事与规则</h1></div></div><div class="league-overview">${regions.map(region=>panel(region.name,leagues.filter(l=>l.region===region.id).map(l=>`<article class="league-system-card"><strong>${l.name}</strong><span>${l.system} · ${l.levels.reduce((s,d)=>s+d.teams,0)} 队</span><small>${isMetroLeague(l.id)?'每联赛前四进入星冠季后赛':`全球冠军杯 ${l.globalSlots} 席`}</small><div class="league-entry-actions">${link(`leagues/${l.id}/1/overview`,'赛事总览 ↗')}${link(`leagues/${l.id}/1/rules`,'赛制规则 ↗')}</div></article>`).join(''))).join('')}${panel(METRO_CHAMPIONS.name,list([['参赛','三联赛各前四，共12队'],['争冠组','每队8场跨联赛比赛，四主四客'],['淘汰赛','前四晋级，1对4、2对3；冠军获得星冠杯'],['全球冠军杯','冠军、亚军、其余两支四强及争冠组第5、6名']])+link('match/overview/metro-champions','星冠季后赛 · 赛事总览 ↗','football-link'))}${panel(GLOBAL_CUP.name,list([['参赛','16队 · 每四年一届'],['赛制','4组单循环，前二晋级；八强起单场淘汰'],['名额','大都会6 / 新四川4 / 利玛4 / 利柏林2'],['分组',GLOBAL_CUP.draw],['资格',GLOBAL_CUP.qualification],['决胜',GLOBAL_CUP.final]])+link('match/overview/global-cup','全球冠军杯 · 赛事总览 ↗','football-link'))}</div>`;}
function rules(system,d){const lower=system.levels.find(l=>l.tier===d.tier+1),upper=system.levels.find(l=>l.tier===d.tier-1),metro=isMetroLeague(system.id);
 return panel('联赛赛制',list([['规模',`${d.teams}队 · ${d.rounds}轮 · ${d.matches}场`],['赛程',d.legs===2?'主客场双循环':'单循环；单数参赛队每轮一队轮空'],['积分','胜3分 / 平1分 / 负0分'],['同分',system.tiebreak.join(' → ')],['冠军',metro?'常规赛第一；前四参加星冠季后赛':system.playoffs?system.playoffs.champion:'最终积分榜第一'],['升级',upper?d.promotion?.playoff?.length?`前${d.promotion.automatic}名直接升入${upper.name}，第${d.promotion.playoff[0]}—${d.promotion.playoff.at(-1)}名附加赛`:`前${d.promotion.automatic}名直接升入${upper.name}`:'无'],['降级',lower?`末${d.relegation}名降入${lower.name}`:'无自动降级'],['全球冠军杯',metro?'按星冠季后赛最终排名取六队':d.tier===1?`年度排名前${system.globalSlots}名`:'无直接资格'],['注册窗口',system.calendar.registration.join(' / ')]]))+
 (metro?panel(METRO_CHAMPIONS.name,list([['资格','三联赛各前四，共12队'],['赛程','每队8场，只对阵其他两个联赛的球队，四主四客'],['晋级','争冠组前四参加半决赛，1对4、2对3'],['冠军','决赛胜者获得星冠杯']])):system.playoffs?panel(system.finalName,list([['资格',`常规赛前${system.playoffs.teams}名`],['赛制','固定签表单场淘汰，最高种子对最低种子'],['主场',system.playoffs.home],['决胜',system.playoffs.tied]])):'')+
 (system.draft?panel('大都会学院选秀',list([['规模',`${system.draft.teams}队 × ${system.draft.rounds}轮，共${system.draft.picks}签`],['资格',system.draft.eligibility],['顺位',system.draft.order],['签约',system.draft.contract]])):panel('球员入口',`<p>${system.entry}</p>`))+
 panel('报名与纪律',list([['名单','成年球员最多25人；至少8名本地培养球员，不足时相应减少注册上限；U21免占名额'],['比赛名单','11名首发 + 最多12名替补'],['换人','5人、3个比赛中窗口'],['纪律','同赛事累计5黄停赛1场；红牌至少停赛1场'],['重置',system.discipline.reset]]));
}
function clubsView(d){const ids=peekSeason()?.members[d.id]||clubs.filter(c=>c.division===d.id).map(c=>c.id);return `<div class="league-clubs" data-sort-list="name">${ids.map(id=>{const c=byId(id),city=cities.find(x=>x.id===c.city),province=provinces.find(x=>x.id===city.province);return link(`squad/${c.id}`,`<b>${esc(c.name)}</b><span>${province.name} · ${city.name}</span><small>${c.founded} 年成立 · 查看阵容 ↗</small>`);}).join('')}</div>`;}
function view(){const {system,division:d,tab}=context();if(!system)return overview();return `<div class="football-title"><div><small>${regions.find(r=>r.id===system.region).name} · ${peekSeason()?.year||YEAR} 赛季</small><h1>${system.name}</h1></div>${link('leagues/all','全部赛事 ↗','football-link')}</div><nav class="league-levels">${system.levels.map(l=>link(`leagues/${system.id}/${l.tier}/${tab}`,l.name,d.id===l.id?'active':'')).join('')}</nav><div class="league-facts">${fact('参赛队',d.teams)}${fact('常规赛',d.rounds+' 轮')}${fact('本级场次',d.matches)}${fact('体系',system.system)}</div><nav class="league-tabs">${[['overview','赛事总览'],['rules','赛制'],['table','积分榜'],['fixtures','赛程'],['clubs','俱乐部'],...(system.playoffs||isMetroLeague(system.id)?[['cup',isMetroLeague(system.id)?'星冠季后赛':'季后赛']]:[])].map(([id,label])=>link(`leagues/${system.id}/${d.tier}/${id}`,label,tab===id?'active':'')).join('')}</nav><div id="league-notice" role="status"></div>${tab==='clubs'?clubsView(d):rules(system,d)}`;}
function draw(){if(root)root.innerHTML=view();}
export function renderLeagues(){return '<section id="league-root" class="football-page"></section>';}
export function disposeLeagues(){generation++;root=null;}
export async function mountLeagues(){root=document.querySelector('#league-root');const token=++generation;const {system,division:d,tab}=context();if(system&&['overview','table','fixtures','cup','playoffs'].includes(tab)){const key=tab==='cup'?(system.cup?.id||(isMetroLeague(system.id)?'metro-champions':`${system.id}-playoffs`)):tab==='playoffs'?`${d.id}-playoffs`:d.id;location.replace(`#match/${tab==='overview'?'overview':tab==='table'?'table':tab==='fixtures'?'schedule':'bracket'}/${key}`);return;}try{await loadSeason();}catch{}if(token===generation)draw();}
