import {leagues,clubs,YEAR,regions,provinces,cities} from '../world.js';
import {loadSeason,peekSeason} from './store.js';
import {GLOBAL_CUP} from './catalog.js';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const byId=id=>clubs.find(c=>c.id===id),link=(url,label,cls='')=>`<a class="${cls}" href="#${url}">${label}</a>`;
let root=null,generation=0;
function context(){const [,systemId='all',tier='1',tab='rules',r='1']=location.hash.split('/');const system=leagues.find(s=>s.id===systemId);const division=system?.levels.find(d=>d.tier===Number(tier))||system?.levels[0];return {systemId,system,division,tab,r:Math.max(1,Number(r)||1)};}
const fact=(label,value)=>`<div><small>${label}</small><strong>${value}</strong></div>`;
const panel=(title,body)=>`<section class="league-panel"><h2>${title}</h2>${body}</section>`;
const list=rows=>`<dl class="league-rules">${rows.map(([k,v])=>`<div><dt>${k}</dt><dd>${v}</dd></div>`).join('')}</dl>`;
function overview(){return `<div class="football-title"><div><small>${peekSeason()?.year||YEAR} 赛季</small><h1>赛事体系</h1></div></div><div class="league-overview">${regions.map(region=>panel(region.name,leagues.filter(l=>l.region===region.id).map(l=>link(`leagues/${l.id}/1/rules`,`<strong>${l.name}</strong><span>${l.system} · ${l.levels.length} 个级别 · ${l.levels.reduce((s,d)=>s+d.teams,0)} 队</span><small>全球冠军杯 ${l.globalSlots} 席</small>`,'league-system-card')).join(''))).join('')}${panel(GLOBAL_CUP.name,`${list([['参赛','32 队 · 上赛季联赛资格'],['赛制','8 组单循环，前二晋级；十六强起单场淘汰'],['赛历','六月集中赛会制'],['名额',leagues.map(l=>`${l.name} ${l.globalSlots}`).join(' / ')],['分组',GLOBAL_CUP.draw],['资格递补','仅按同一体系联赛排名顺延，不跨体系转移名额'],['同分',GLOBAL_CUP.tiebreak.join(' → ')],['决胜',GLOBAL_CUP.final]])}`)}</div>`;}
function rules(system,d){const lower=system.levels.find(l=>l.tier===d.tier+1),upper=system.levels.find(l=>l.tier===d.tier-1);
 return `${panel('联赛赛制',list([['规模',`${d.teams} 队 · ${d.rounds} 轮 · ${d.matches} 场`],['赛程','主客场双循环，每对球队各主场一次'],['积分','胜 3 分 / 平 1 分 / 负 0 分'],['同分',system.tiebreak.join(' → ')],['冠军',system.id==='closed'?system.playoffs.champion:'最终积分榜第一名'],['升级',upper?`前二直接升级；第 3—6 名争夺最后一席，升入${upper.name}`:'无'],['降级',lower?`末 ${d.relegation} 名降入${lower.name}`:'无自动降级'],['全球杯',d.tier===1?`前 ${system.globalSlots} 名取得下一年度资格${system.id==='closed'?'（按常规赛排名）':''}`:'无直接资格'],['赛历','3—11 月；六月全球杯期间休赛。常规周末开赛，密集轮次安排周中'],['注册窗口',system.calendar.registration.join(' / ')]]))}
 ${panel(system.id==='closed'?'季后赛':'升级附加赛',list([['参赛',system.id==='closed'?'常规赛前八':'各下级联赛第 3—6 名'],['对阵',system.playoffs.pairs.map(([a,b])=>`${a} 对 ${b}`).join(' / ')],['主场',system.playoffs.home],['决胜',system.playoffs.tied],['轮次',system.id==='closed'?'八强 → 半决赛 → 决赛；固定签表不重排':'半决赛 → 决赛；胜者获第三个升级名额']]))}
 ${system.cup?panel(system.cup.name,list([['资格',system.cup.eligibility],['规模',`${clubs.filter(c=>c.league===system.id).length} 队`],['抽签',system.cup.draw],['赛制','全部单场；抽签先列者主场，决赛中立场'],['决胜',system.cup.tied],['全球杯','冠军不另获名额'],['赛历','3—11 月穿插进行，六月停赛']])):''}
 ${system.draft?panel('学院选秀',list([['时间','每年 1 月'],['规模','16 队 × 3 轮，共 48 签'],['资格',system.draft.eligibility],['顺位',system.draft.order],['抽签','末八队前三签权重：24 / 20 / 16 / 12 / 10 / 8 / 6 / 4，逐签无放回'],['签约',system.draft.contract]])):panel('球员入口',`<p>${system.entry}</p>`)}
 ${panel('报名与纪律',list([['名单','成年球员最多 25 人；至少 8 名本地培养球员，不足时相应减少注册上限；U21 免占名额'],['本地培养','15—21 岁期间在本体系俱乐部或学院累计培养满三年，与出生地和姓名语系无关'],['比赛名单','11 名首发 + 最多 12 名替补'],['换人','5 人、3 个比赛中窗口；半场不占窗口，加时不增加名额'],['纪律','同赛事累计 5 黄停赛 1 场；红牌至少停赛 1 场，严重违纪由纪律委员会追加'],['公平竞赛分','每张黄牌 1 分、每张红牌 3 分；分数少者优先'],['重置',system.discipline.reset],['准入',system.entry]]))}`;
}
function clubsView(d){const ids=peekSeason()?.members[d.id]||clubs.filter(c=>c.division===d.id).map(c=>c.id);return `<div class="league-clubs">${ids.map(id=>{const c=byId(id),city=cities.find(x=>x.id===c.city),province=provinces.find(x=>x.id===city.province);return link(`squad/${c.id}`,`<b>${esc(c.name)}</b><span>${province.name} · ${city.name}</span><small>${c.founded} 年成立 · 查看阵容 ↗</small>`);}).join('')}</div>`;}
function view(){const {system,division:d,tab}=context();if(!system)return overview();return `<div class="football-title"><div><small>${regions.find(r=>r.id===system.region).name} · ${peekSeason()?.year||YEAR} 赛季</small><h1>${system.name}</h1></div>${link('leagues/all','全部赛事 ↗','football-link')}</div><nav class="league-levels">${system.levels.map(l=>link(`leagues/${system.id}/${l.tier}/${tab}`,l.name,d.id===l.id?'active':'')).join('')}</nav><div class="league-facts">${fact('参赛队',d.teams)}${fact('常规赛',d.rounds+' 轮')}${fact('本级场次',d.matches)}${fact('体系',system.system)}</div><nav class="league-tabs">${[['rules','赛制'],['table','积分榜'],['fixtures','赛程'],['clubs','俱乐部'],['cup',system.cup?'杯赛':'季后赛'],...(d.promotion?[['playoffs','升级附加赛']]:[])].map(([id,label])=>link(`leagues/${system.id}/${d.tier}/${id}`,label,tab===id?'active':'')).join('')}</nav><div id="league-notice" role="status"></div>${tab==='clubs'?clubsView(d):rules(system,d)}`;}
function draw(){if(root)root.innerHTML=view();}
export function renderLeagues(){return '<section id="league-root" class="football-page"></section>';}
export function disposeLeagues(){generation++;root=null;}
export async function mountLeagues(){root=document.querySelector('#league-root');const token=++generation;const {system,division:d,tab}=context();if(system&&['table','fixtures','cup','playoffs'].includes(tab)){const key=tab==='cup'?(system.cup?.id||'closed-playoffs'):tab==='playoffs'?`${d.id}-playoffs`:d.id;location.replace(`#match/${tab==='table'?'table':tab==='fixtures'?'schedule':'bracket'}/${key}`);return;}try{await loadSeason();}catch{}if(token===generation)draw();}
