import {clubs,academies} from '../world.js';
import {ATTRIBUTE_GROUPS,POSITIONS,rating} from '../football/players.js';
import {bodyDevelopmentMarkup,workloadMarkup} from '../football/development-ui.js';
import {loadSeason,peekSeason,saveYouthPath,saveYouthObservation,saveAcademyPlan} from './store.js';
import {academyReport} from './academy.js';
import {registeredPlayer} from './registry.js';
import {youthPlayers,youthOpportunities,youthObservation} from './youth.js';
import {developedPlayer,developmentReport} from './development.js';

const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const clubName=id=>clubs.find(c=>c.id===id)?.name||academies.find(a=>a.id===id)?.name||'自由球员';
const tabs=[['academy','本队青训'],['senior','已提拔'],['loan','外租'],['candidates','自由球员'],['draft','学院与选秀'],['history','培养记录']];
const statusNames={academy:'青训',youth:'青训',senior:'一线队',loan:'外租',free:'自由球员',released:'自由球员',draft:'待选秀',retired:'已退出'};
const actionNames={retain:'留青训',promote:'提拔至一线队',loan:'安排外租',release:'释放球员',sign:'签入球队'};
let root=null,generation=0,cleanup=()=>{},busy=false,notice='',query='',page=0;
const currentRoute=()=>{const [,tab='academy',id]=location.hash.split('/');return {tab:tabs.some(([key])=>key===tab)?tab:'academy',selectedId:id?decodeURIComponent(id):undefined};};
const registration=(s,id)=>s.playerRegistry?.registrations?.[id]||{};
const affiliation=(s,p)=>{const r=registration(s,p.id);return r.pathway==='royal'&&r.status==='youth'?clubName(r.academyId):clubName(p.club);};
const playerLink=(p,tab)=>`#youth/${tab}/${encodeURIComponent(p.id)}`;
function eventText(event){return event.text||({intake:'加入青训',promote:'提拔至一线队',retain:'继续青训',loan:'外租',release:'释放球员',sign:'签约',return:'租借归队',loanReturn:'租借归队',draft:'选秀签约',undrafted:'选秀落选',retire:'退出职业人才池',observe:'更新观察'}[event.type]||'培养记录');}
function historyMarkup(s,id){const events=(s.playerRegistry?.events||[]).filter(event=>!id||event.playerId===id);if(id)for(const h of registration(s,id).history||[])if(!events.some(e=>e.date===h.date))events.push({playerId:id,date:h.date,clubId:h.clubId,text:`注册状态：${statusNames[h.status]||h.status}`});events.sort((a,b)=>a.date.localeCompare(b.date));events.reverse();events.splice(60);return events.length?`<ol class="youth-history">${events.map(event=>{const p=registeredPlayer(s,event.playerId);return `<li><time>${esc(event.date)}</time><div>${!id&&p?`<a href="${playerLink(p,'history')}">${esc(p.name)}</a>`:''}<strong>${esc(eventText(event))}</strong>${event.clubId?`<span>${esc(clubName(event.clubId))}</span>`:''}${event.overall?`<span>第 ${event.overall} 顺位</span>`:''}</div></li>`;}).join('')}</ol>`:'<p class="youth-empty">暂无培养记录</p>';}
function draftMarkup(s){const drafts=(s.playerRegistry?.drafts||[]).slice().reverse();return `<section class="youth-drafts"><h2>年度选秀</h2>${drafts.length?drafts.map((draft,i)=>`<details ${i===0?'open':''}><summary>${draft.year} 年 · ${draft.picks.length} 人获选 · ${draft.undrafted.length} 人落选</summary><div class="youth-draft-table"><table><thead><tr><th>顺位</th><th>球员</th><th>签约权球队</th></tr></thead><tbody>${draft.picks.map(pick=>{const p=registeredPlayer(s,pick.playerId);return `<tr><td>${pick.overall}</td><td><a href="#youth/draft/${esc(pick.playerId)}">${esc(p?.name||'球员')}</a></td><td>${esc(clubName(pick.club))}</td></tr>`;}).join('')}</tbody></table></div></details>`).join(''):'<p class="youth-caption">本季选秀尚未开始</p>'}</section>`;}
function observationMarkup(s,p){const report=youthObservation(s,p.id);if(!report)return '<p class="youth-empty">尚未建立观察报告</p>';return `<div class="youth-forecast"><div><span>预计成年能力</span><strong>${Math.round(report.forecastLow)}–${Math.round(report.forecastHigh)}</strong></div><div><span>评估把握</span><strong>${esc(({low:'较低',medium:'中等',high:'较高'})[report.confidence]||report.confidence)}</strong></div></div><p class="youth-caption">${report.updatedAt?`${esc(report.updatedAt)} · `:''}已观察 ${report.observedMatches??0} 场</p>${report.notes?.length?`<ul class="youth-notes">${report.notes.map(note=>`<li>${esc(note)}</li>`).join('')}</ul>`:''}`;}
function academyMarkup(s){
 const report=academyReport(s,s.manager.clubId),disabled=busy||s.activeMatch?'disabled':'';
 if(!report.managed)return '<section class="youth-academy"><h2>皇家学院培养</h2><p class="youth-caption">训练与选人由学院负责</p></section>';
 const environment=report.quality>=1.04?'完善':report.quality>=1?'标准':'基础',selectionNote={balanced:'兼顾当前能力与轮换',development:'增加年轻球员轮换机会',competitive:'优先当前能力，减少轮换'}[report.selection];
 return `<section class="youth-academy"><div class="youth-academy-heading"><h2>培养计划</h2><span>重点培养 ${report.focusPlayers.length} / ${report.focusCapacity}</span></div><div class="youth-academy-plan"><label>青年选人策略<select data-academy-selection aria-label="青年选人策略" ${disabled}>${[['balanced','均衡轮换'],['development','优先培养'],['competitive','优先竞争']].map(([key,label])=>`<option value="${key}" ${report.selection===key?'selected':''}>${label}</option>`).join('')}</select><small>${selectionNote}</small></label><div><span>培养环境</span><strong>${environment}</strong></div></div><p class="youth-caption">重点球员增加指导时间，其他青年相应减少 · 调整次日生效</p></section>`;
}
function focusMarkup(s,p,disabled){
 const report=academyReport(s,s.manager.clubId);if(!report.managed||!report.players.some(player=>player.id===p.id))return '';
 const focused=report.focusPlayers.includes(p.id),full=!focused&&report.focusPlayers.length>=report.focusCapacity;
 return `<div class="youth-focus"><button data-youth-action="focus" data-player="${esc(p.id)}" aria-pressed="${focused}" ${disabled||full?'disabled':''}>${focused?'取消重点培养':'列为重点培养'}</button><span>${focused?'重点培养':full?'重点名额已满':`剩余 ${report.focusCapacity-report.focusPlayers.length} 个名额`}</span></div>`;
}
function detail(s,p,tab){
 const reg=registration(s,p.id),report=developmentReport(s,p),opportunities=youthOpportunities(s,p.id),actions=opportunities.actions||[],loans=opportunities.loans||[];
 const disabled=busy||s.activeMatch?'disabled':'';
 return `<article class="youth-detail"><header><div><span class="youth-kicker">${esc(statusNames[reg.status]||reg.status||'青训')}</span><h2>${esc(p.name)}</h2><p>${p.age} 岁 · ${POSITIONS[p.position]} · ${esc(affiliation(s,p))}</p></div><div class="youth-ability"><strong>${rating(p)}</strong><span>当前能力</span></div></header><div class="youth-minutes"><div><strong>${Math.round(report?.youthMinutes||0)}</strong><span>本季青年分钟</span></div><div><strong>${Math.round(report?.minutes||0)}</strong><span>本季正式分钟</span></div><div><strong>${report?.gain>=0?'+':''}${(report?.gain||0).toFixed(1)}</strong><span>本季能力变化</span></div></div>
 ${bodyDevelopmentMarkup(report?.body)}${workloadMarkup(report?.workload)}
 <section><h3>发展观察</h3>${observationMarkup(s,p)}${opportunities.canObserve?`<button data-youth-action="observe" data-player="${esc(p.id)}" ${disabled}>更新观察</button>`:''}</section>
 <section><h3>培养安排</h3>${focusMarkup(s,p,disabled)}${s.activeMatch?'<p class="youth-caption">比赛结束后可调整</p>':''}<div class="youth-actions">${actions.filter(action=>action!=='loan').map(action=>`<button data-youth-action="${esc(action)}" data-player="${esc(p.id)}" ${disabled}>${actionNames[action]||esc(action)}</button>`).join('')}</div>${actions.includes('loan')&&loans.length?`<div class="youth-loan"><label>外租球队<select data-loan-target aria-label="外租球队" ${disabled}>${loans.map(t=>`<option value="${esc(t.id)}">${esc(t.name||clubName(t.id))}</option>`).join('')}</select></label><button data-youth-action="loan" data-player="${esc(p.id)}" ${disabled}>安排外租</button></div>`:''}${opportunities.reason||!actions.length?`<p class="youth-caption">${esc(opportunities.reason||'暂无可调整安排')}</p>`:''}</section>
 <details class="youth-attributes"><summary>竞技属性</summary><div>${Object.entries(ATTRIBUTE_GROUPS).filter(([key])=>key!=='goalkeeper'||p.position==='GK').map(([,group])=>`<section><h3>${group.label}</h3>${Object.entries(group.fields).map(([key,label])=>`<p><span>${label}</span><b>${Math.round(p.attributes[key])}</b></p>`).join('')}</section>`).join('')}</div></details>
 <details class="youth-player-history" open><summary>生涯记录</summary>${historyMarkup(s,p.id)}</details>${p.club?`<a class="football-link" href="#squad/${esc(p.club)}/${esc(p.id)}">完整球员档案 ↗</a>`:''}</article>`;
}
export function youthContent(s,{tab='academy',selectedId,search='',pageIndex=0}={}){
 if(!s.manager)return '<header class="football-title"><h1>青训中心</h1></header><section class="youth-detail"><h2>尚未接手俱乐部</h2><a class="football-primary" href="#manager">前往经理首页</a></section>';
 const own=s.manager.clubId,displayTabs=tabs.map(([key,label])=>[key,key==='academy'&&clubs.find(c=>c.id===own)?.league==='closed'?'关联学院':label]),all=youthPlayers(s,own).map(p=>developedPlayer(s,p)),global=Object.keys(s.playerRegistry?.players||{}).map(id=>registeredPlayer(s,id)).filter(Boolean).map(p=>developedPlayer(s,p));
 const sets={academy:all.filter(p=>['academy','youth'].includes(registration(s,p.id).status)&&p.club===own),senior:all.filter(p=>registration(s,p.id).status==='senior'&&p.club===own),loan:all.filter(p=>registration(s,p.id).status==='loan'&&registration(s,p.id).ownerClubId===own),candidates:global.filter(p=>['free','released'].includes(registration(s,p.id).status)),draft:global.filter(p=>registration(s,p.id).pathway==='royal'),history:global.filter(p=>{const r=registration(s,p.id);return r.academyClubId===own||r.ownerClubId===own||r.clubId===own||r.rightsClubId===own;})};
 const candidates=sets[tab]||sets.academy,filtered=candidates.filter(p=>!search||p.name.toLocaleLowerCase().includes(search.toLocaleLowerCase())||POSITIONS[p.position].includes(search)),maxPage=Math.max(0,Math.ceil(filtered.length/24)-1),safePage=Math.min(pageIndex,maxPage),list=filtered.slice(safePage*24,(safePage+1)*24);
 const selected=(selectedId?filtered.find(p=>p.id===selectedId):null)||list[0];
 return `<header class="football-title"><div><small>${s.year} 赛季 · ${esc(clubName(own))}</small><h1>青训中心</h1></div><a class="football-link" href="#manager">经理首页 ↗</a></header><nav class="youth-tabs" aria-label="青训中心栏目">${displayTabs.map(([key,label])=>`<a href="#youth/${key}" ${key===tab?'aria-current="page"':''}>${label}<span>${sets[key]?.length||0}</span></a>`).join('')}</nav><p class="youth-status" role="status" aria-live="polite">${esc(notice||'本地自动存档')}</p>${tab==='academy'?academyMarkup(s):''}${tab==='draft'?`<p class="youth-caption">皇家学院 → 星冠联盟选秀 · 俱乐部青训 → 一线队</p>${draftMarkup(s)}`:''}<div class="youth-layout"><section class="youth-list"><label class="youth-search">球员筛选<input type="search" data-youth-search value="${esc(search)}" placeholder="姓名或位置" aria-label="筛选青训球员"></label><div class="youth-list-heading"><span>${filtered.length} 名球员</span><span>当前能力</span></div>${list.map(p=>{const reg=registration(s,p.id);return `<a href="${playerLink(p,tab)}" class="youth-row ${selected?.id===p.id?'selected':''}" ${selected?.id===p.id?'aria-current="true"':''}><span><strong>${esc(p.name)}</strong><small>${p.age} 岁 · ${POSITIONS[p.position]} · ${esc(statusNames[reg.status]||reg.status)}</small><small>${esc(affiliation(s,p))}</small></span><b>${rating(p)}</b></a>`;}).join('')||'<p class="youth-empty">暂无符合条件的球员</p>'}${maxPage?`<div class="youth-pagination"><button data-youth-page="${safePage-1}" ${safePage===0?'disabled':''}>上一页</button><span>${safePage+1} / ${maxPage+1}</span><button data-youth-page="${safePage+1}" ${safePage===maxPage?'disabled':''}>下一页</button></div>`:''}</section>${selected?detail(s,selected,tab):`<section class="youth-detail"><h2>${displayTabs.find(([key])=>key===tab)?.[1]||'青训球员'}</h2><p class="youth-empty">暂无球员</p>${tab==='history'?historyMarkup(s):''}</section>`}</div>`;
}
function draw(){if(root)root.innerHTML=youthContent(peekSeason(),{...currentRoute(),search:query,pageIndex:page});}
export function renderYouth(){return '<section class="football-page youth-page" id="youth-root"><p role="status">正在读取青训…</p></section>';}
export function disposeYouth(){generation++;cleanup();root=null;busy=false;}
export async function mountYouth(){
 root=document.querySelector('#youth-root');if(!root)return;const token=++generation;
 try{await loadSeason();if(token!==generation)return;draw();}catch(error){if(token===generation&&root)root.innerHTML=`<h1>青训中心</h1><p role="alert">${esc(error.message)}</p>`;return;}
 const click=async ev=>{const button=ev.target.closest('button');if(!button)return;if(button.hasAttribute('data-youth-page')){page=Number(button.dataset.youthPage);draw();return;}const action=button.dataset.youthAction;if(!action||busy)return;const id=button.dataset.player,clubId=action==='loan'?root.querySelector('[data-loan-target]')?.value:peekSeason().manager?.clubId;busy=true;notice='正在保存…';draw();
  try{if(action==='observe')await saveYouthObservation(id);else if(action==='focus'){const plan=academyReport(peekSeason(),peekSeason().manager.clubId),focusPlayers=plan.focusPlayers.includes(id)?plan.focusPlayers.filter(value=>value!==id):[...plan.focusPlayers,id];await saveAcademyPlan({focusPlayers});}else await saveYouthPath(id,action,{clubId});if(token!==generation)return;notice='已保存';if(action!=='observe'&&action!=='retain'&&action!=='focus'){const nextTab=({promote:'senior',loan:'loan',release:'candidates',sign:'senior'})[action];query='';page=0;if(nextTab)location.hash=`youth/${nextTab}/${encodeURIComponent(id)}`;}}
  catch(error){if(token!==generation)return;notice=error.message;}
  finally{if(token===generation){busy=false;draw();}}
 };
 const input=ev=>{if(!ev.target.hasAttribute('data-youth-search'))return;query=ev.target.value;page=0;const caret=ev.target.selectionStart;draw();const field=root.querySelector('[data-youth-search]');field.focus({preventScroll:true});field.setSelectionRange(caret,caret);};
 const change=async ev=>{if(!ev.target.hasAttribute('data-academy-selection')||busy)return;const selection=ev.target.value;busy=true;notice='正在保存…';draw();try{await saveAcademyPlan({selection});if(token===generation)notice='已保存 · 次日生效';}catch(error){if(token===generation)notice=error.message;}finally{if(token===generation){busy=false;draw();}}};
 root.addEventListener('click',click);root.addEventListener('input',input);root.addEventListener('change',change);const mounted=root;cleanup=()=>{mounted.removeEventListener('click',click);mounted.removeEventListener('input',input);mounted.removeEventListener('change',change);};
}
