// Curated from Faker v9.9.0 locale dictionaries; Chinese readings authored for AstraBall.
// Full upstream data and license: third_party/faker/.
const pairs=text=>text.split('|').map(part=>{const [original,zh]=part.split('=');return {original,zh};});
const tradition=(label,first,last)=>({label,first:pairs(first),last:pairs(last)});
export const NAME_POOLS={
 zh:tradition('汉语','知远=知远|明川=明川|柏舟=柏舟|启辰=启辰|远航=远航|景行=景行|泽宇=泽宇|云帆=云帆|知衡=知衡|承安=承安|望舒=望舒|时雨=时雨|怀瑾=怀瑾|星野=星野|沐阳=沐阳|庭山=庭山|砚清=砚清|书言=书言|浩然=浩然|凌风=凌风|庭岳=庭岳|少卿=少卿|清和=清和|文钧=文钧','沈=沈|陆=陆|许=许|周=周|林=林|陈=陈|方=方|顾=顾|叶=叶|江=江|白=白|程=程|黎=黎|赵=赵|吴=吴|梁=梁|宋=宋|徐=徐|谢=谢|唐=唐|罗=罗|何=何|段=段|钟=钟'),
 en:tradition('英语','Adam=亚当|Aaron=阿伦|Arthur=阿瑟|Benjamin=本杰明|Caleb=凯莱布|Daniel=丹尼尔|David=戴维|Edward=爱德华|Ethan=伊桑|Felix=费利克斯|George=乔治|Henry=亨利|Isaac=艾萨克|Jack=杰克|James=詹姆斯|Leo=利奥|Liam=利亚姆|Nathan=内森|Oliver=奥利弗|Oscar=奥斯卡|Samuel=塞缪尔|Thomas=托马斯|William=威廉|Noah=诺亚','Adams=亚当斯|Allen=艾伦|Baker=贝克|Bennett=班尼特|Brooks=布鲁克斯|Brown=布朗|Carter=卡特|Clark=克拉克|Collins=柯林斯|Cooper=库珀|Davis=戴维斯|Evans=埃文斯|Foster=福斯特|Gray=格雷|Green=格林|Harris=哈里斯|Hill=希尔|King=金|Lewis=刘易斯|Morgan=摩根|Parker=帕克|Reed=里德|Scott=斯科特|Wilson=威尔逊'),
 de:tradition('德语','Adrian=阿德里安|Alexander=亚历山大|Anton=安东|Bastian=巴斯蒂安|Benedikt=本尼迪克特|David=达维德|Emil=埃米尔|Felix=费利克斯|Florian=弗洛里安|Friedrich=弗里德里希|Henrik=亨里克|Jakob=雅各布|Johann=约翰|Jonas=约纳斯|Julian=尤利安|Karl=卡尔|Leon=莱昂|Lukas=卢卡斯|Maximilian=马克西米利安|Moritz=莫里茨|Niklas=尼克拉斯|Paul=保罗|Simon=西蒙|Tobias=托比亚斯','Bauer=鲍尔|Becker=贝克尔|Braun=布劳恩|Fischer=菲舍尔|Hoffmann=霍夫曼|Keller=凯勒|Klein=克莱因|Koch=科赫|Krause=克劳泽|Krüger=克吕格尔|Lang=朗格|Lange=朗格|Meyer=迈耶|Müller=穆勒|Neumann=诺伊曼|Richter=里希特|Schmidt=施密特|Schneider=施奈德|Schulz=舒尔茨|Schwarz=施瓦茨|Vogel=福格尔|Wagner=瓦格纳|Weber=韦伯|Wolf=沃尔夫'),
 fr:tradition('法语','Adrien=阿德里安|Alexandre=亚历山大|Antoine=安托万|Baptiste=巴蒂斯特|Clément=克莱芒|Damien=达米安|Émile=埃米尔|Étienne=埃蒂安|Gabriel=加布里埃尔|Hugo=雨果|Jules=朱尔|Julien=朱利安|Laurent=洛朗|Louis=路易|Lucas=卢卡|Mathieu=马蒂厄|Maxime=马克西姆|Nicolas=尼古拉|Olivier=奥利维耶|Pierre=皮埃尔|Quentin=康坦|Raphaël=拉斐尔|Théo=泰奥|Victor=维克托','Aubert=奥贝尔|Bernard=贝尔纳|Bertrand=贝特朗|Blanc=布朗|Bonnet=博内|Boyer=布瓦耶|Chevalier=舍瓦利耶|Colin=科兰|Deschamps=德尚|Dubois=迪布瓦|Dufour=迪富尔|Dumas=迪马|Dumont=迪蒙|Dupont=迪蓬|Durand=迪朗|Faure=福尔|Fontaine=方丹|Fournier=富尼耶|Garnier=加尼耶|Girard=吉拉尔|Lambert=朗贝尔|Laurent=洛朗|Lefebvre=勒费弗尔|Martin=马丁'),
 es:tradition('西班牙语','Alejandro=亚历杭德罗|Alonso=阿隆索|Andrés=安德烈斯|Antonio=安东尼奥|Carlos=卡洛斯|Daniel=丹尼尔|Diego=迭戈|Eduardo=爱德华多|Enrique=恩里克|Felipe=费利佩|Fernando=费尔南多|Francisco=弗朗西斯科|Gabriel=加布里埃尔|Javier=哈维尔|Jorge=豪尔赫|José=何塞|Juan=胡安|Luis=路易斯|Manuel=曼努埃尔|Miguel=米格尔|Pablo=巴勃罗|Pedro=佩德罗|Rafael=拉斐尔|Sergio=塞尔希奥','Alonso=阿隆索|Álvarez=阿尔瓦雷斯|Castro=卡斯特罗|Cruz=克鲁斯|Díaz=迪亚斯|Fernández=费尔南德斯|Flores=弗洛雷斯|García=加西亚|Gómez=戈麦斯|González=冈萨雷斯|Gutiérrez=古铁雷斯|Hernández=埃尔南德斯|Jiménez=希门尼斯|López=洛佩斯|Martín=马丁|Martínez=马丁内斯|Moreno=莫雷诺|Navarro=纳瓦罗|Ortega=奥尔特加|Pérez=佩雷斯|Ramírez=拉米雷斯|Rodríguez=罗德里格斯|Sánchez=桑切斯|Torres=托雷斯'),
 pt_BR:tradition('葡萄牙语','Adriano=阿德里亚诺|Alexandre=亚历山德雷|André=安德烈|Antônio=安东尼奥|Bruno=布鲁诺|Carlos=卡洛斯|Daniel=丹尼尔|Diego=迭戈|Eduardo=爱德华多|Felipe=费利佩|Fernando=费尔南多|Gabriel=加布里埃尔|Gustavo=古斯塔沃|Henrique=恩里克|João=若昂|José=若泽|Lucas=卢卡斯|Luiz=路易斯|Marcelo=马塞洛|Miguel=米格尔|Paulo=保罗|Pedro=佩德罗|Rafael=拉斐尔|Ricardo=里卡多','Albuquerque=阿尔布开克|Barros=巴罗斯|Batista=巴蒂斯塔|Braga=布拉加|Carvalho=卡瓦略|Costa=科斯塔|Franco=弗兰科|Macedo=马塞多|Martins=马丁斯|Melo=梅洛|Moraes=莫赖斯|Moreira=莫雷拉|Nogueira=诺盖拉|Oliveira=奥利维拉|Pereira=佩雷拉|Reis=雷斯|Santos=桑托斯|Saraiva=萨赖瓦|Silva=席尔瓦|Souza=索萨|Xavier=沙维尔'),
 ru:tradition('斯拉夫语','Александр=亚历山大|Алексей=阿列克谢|Анатолий=阿纳托利|Андрей=安德烈|Антон=安东|Борис=鲍里斯|Вадим=瓦季姆|Виктор=维克托|Виталий=维塔利|Владимир=弗拉基米尔|Денис=杰尼斯|Дмитрий=德米特里|Евгений=叶夫根尼|Иван=伊万|Игорь=伊戈尔|Кирилл=基里尔|Максим=马克西姆|Михаил=米哈伊尔|Никита=尼基塔|Николай=尼古拉|Олег=奥列格|Павел=帕维尔|Роман=罗曼|Сергей=谢尔盖','Абрамов=阿布拉莫夫|Андреев=安德烈耶夫|Белов=别洛夫|Васильев=瓦西里耶夫|Волков=沃尔科夫|Григорьев=格里戈里耶夫|Егоров=叶戈罗夫|Иванов=伊万诺夫|Козлов=科兹洛夫|Кузнецов=库兹涅佐夫|Макаров=马卡罗夫|Михайлов=米哈伊洛夫|Морозов=莫罗佐夫|Николаев=尼古拉耶夫|Орлов=奥尔洛夫|Павлов=帕夫洛夫|Петров=彼得罗夫|Попов=波波夫|Семёнов=谢苗诺夫|Смирнов=斯米尔诺夫|Соколов=索科洛夫|Степанов=斯捷潘诺夫|Фёдоров=费奥多罗夫|Яковлев=雅科夫列夫'),
 ar:tradition('阿拉伯语','أحمد=艾哈迈德|أسامة=乌萨马|أشرف=阿什拉夫|أكرم=阿克拉姆|إبراهيم=易卜拉欣|إسماعيل=伊斯梅尔|أيمن=艾曼|بلال=比拉勒|حسن=哈桑|حسين=侯赛因|خالد=哈立德|رامي=拉米|سامي=萨米|سعيد=赛义德|طارق=塔里克|عادل=阿迪勒|عمر=奥马尔|علي=阿里|فارس=法里斯|كريم=卡里姆|محمد=穆罕默德|محمود=马哈茂德|مصطفى=穆斯塔法|يوسف=优素福','ادريس=伊德里斯|الأشراف=阿什拉夫|البشيري=巴希里|الحمامي=哈马米|الخليفي=赫莱菲|الشريف=谢里夫|الشيباني=谢巴尼|الصغير=萨吉尔|الصفار=萨法尔|الطويل=塔维勒|العطار=阿塔尔|العنابي=安纳比|الغربي=加尔比|القلال=卡拉勒|المحجوب=马赫朱卜|النابلي=纳布利|النجار=纳贾尔|بن حسين=本·侯赛因|بن عاشور=本·阿舒尔|بن عثمان=本·奥斯曼|بن عمر=本·奥马尔|جابالله=贾巴拉|سعيد=赛义德|عاشور=阿舒尔'),
};
