import {seasonTeam} from './competitions/runtime.js';
import {renderManager,mountManager,disposeManager} from './competitions/manager-ui.js';
import {peekSeason,loadSeason} from './competitions/store.js';
import {renderHub,mountHub,disposeHub} from './competitions/hub.js';
import {renderLeagues,mountLeagues,disposeLeagues} from './competitions/ui.js';
import {renderFootball,mountFootball,disposeFootball} from './football/ui.js';
import { renderAtlas, mountAtlas, disposeAtlas } from './atlas.js';
import {YEAR,regions,provinces,cities,leagues,clubs,academies,families,players,drafts,byId,location,playerLeague,hometownPlayers,hometownDrafts,alumni,relatives,originStory} from './world.js';
const app=document.querySelector('#app');
const e=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icon=(name,size=18)=>`<svg width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" aria-hidden="true">${{globe:'<circle cx="12" cy="12" r="9"/><ellipse cx="12" cy="12" rx="4" ry="9"/><path d="M3 12h18M5 7h14M5 17h14"/>',person:'<circle cx="12" cy="8" r="4"/><path d="M4 22v-3a8 8 0 0 1 16 0v3"/>',star:'<path d="m12 3 2.8 5.7 6.2.9-4.5 4.4 1.1 6.2-5.6-3-5.6 3 1.1-6.2L3 9.6l6.2-.9Z"/>',arrow:'<path d="M5 12h14m-6-6 6 6-6 6"/>',back:'<path d="M19 12H5m6-6-6 6 6 6"/>',pin:'<path d="M19 10c0 5-7 11-7 11S5 15 5 10a7 7 0 0 1 14 0Z"/><circle cx="12" cy="10" r="2"/>',school:'<path d="m2 9 10-6 10 6-10 6ZM6 12v6c4 3 8 3 12 0v-6M22 9v8"/>',family:'<circle cx="12" cy="5" r="3"/><path d="M12 8v5M5 17v-4h14v4"/><circle cx="5" cy="20" r="3"/><circle cx="19" cy="20" r="3"/>',cup:'<path d="M7 3h10v7a5 5 0 0 1-10 0ZM7 5H3v3c0 3 2 4 5 4m9-7h4v3c0 3-2 4-5 4m-4 3v6m-5 0h10"/>'}[name]||''}</svg>`;
let watched;
try {watched=new Set(JSON.parse(localStorage.getItem('astraball-watch')||'[]'));}catch{watched=new Set();}
let mode='tier';let placeTab='peers';let routeTrail=[];const viewStates=new Map();let returning=false;let lastRoute=window.location.hash.slice(1)||'manager';
const route=(path,label,cls='')=>`<a class="${cls}" ${cls.includes('nav-item')?`aria-label="${e(label.replace(/<[^>]*>/g,'').trim())}" title="${e(label.replace(/<[^>]*>/g,'').trim())}"`:''} href="#${e(path)}">${label}</a>`;
const playerPath=id=>`player/${id}/place/province/${location(byId(players,id).city).province.id}`;
const current=()=>{const bits=decodeURIComponent(locationHash()).split('/');return {section:bits[0],player:byId(players,bits[1])||players[0],type:bits[2]||'place',kind:bits[3]||'province',id:bits[4]||'yunmin',worldId:bits[1]||'sichuan',entity:bits[3]};};
function locationHash(){return window.location.hash.slice(1)||'manager';}
const linkPlayer=p=>route(playerPath(p.id),e(p.name));
const entityPath=(p,type,id)=>`player/${p.id}/${type}/${id}`;
const empty=text=>`<div class="empty">${icon('globe',28)}<p>${e(text)}</p></div>`;
function badge(text){return `<span class="badge">${e(text)}</span>`;}
function row(p,extra='') {p=currentPlayerView(p);const loc=location(p.city);const club=byId(clubs,p.club||p.lastClub);return route(playerPath(p.id),`<span class="avatar ${p.retired?'retired':''}">${e(p.name.split(' ').pop().slice(0,1))}</span><span class="row-name"><strong>${e(p.name)}</strong><small>${p.age} 岁 · ${e(p.position)} · ${p.retired?'已退役':e(club?.name||'自由球员')}</small></span><span class="row-detail">${e(extra||p.honors[0]?.text||loc.city.name)}</span>${icon('arrow',16)}`,'person-row');}
function shell(body,section,p) {
  return `<aside class="sidebar"><a class="brand" href="#manager"><span class="brand-mark">A<span>✦</span></span><span>ASTRA<span class="brand-light">BALL</span></span></a><nav>${route('manager',`${icon('person')}<span>经理首页</span>`,`nav-item ${['manager','coach'].includes(section)?'selected':''}`)}${route('world/all',`${icon('globe')}<span>世界图鉴</span>`,`nav-item ${section==='world'?'selected':''}`)}${route(playerPath(p.id),`${icon('person')}<span>球员档案</span>`,`nav-item ${section==='player'?'selected':''}`)}${route('leagues/all',`${icon('cup')}<span>赛事体系</span>`,`nav-item ${section==='leagues'?'selected':''}`)}${route('match',`${icon('cup')}<span>比赛中心</span>`,`nav-item ${section==='match'?'selected':''}`)}${route(`squad/${peekSeason()?.manager?.clubId||'sky'}`,`${icon('person')}<span>球队阵容</span>`,`nav-item ${section==='squad'?'selected':''}`)}${route('watch',`${icon('star')}<span>关注名单</span><b>${watched.size}</b>`,`nav-item ${section==='watch'?'selected':''}`)}</nav><div class="sidebar-foot"><span class="live-dot"></span>俱乐部经理</div></aside><div class="workspace"><header class="topbar"><span class="topbar-title">俱乐部经理 <span>/</span> ${section==='manager'?'经理首页':section==='coach'?'执教比赛':section==='world'?'星球档案':section==='watch'?'我的关注':section==='leagues'?'赛事体系':section==='match'?'比赛中心':section==='squad'?'球队阵容':e(p.name)}</span><div class="date"><span>殖民历</span> ${peekSeason()?.year||YEAR} <span>年${peekSeason()?` ${Number(peekSeason().date.slice(5,7))} 月 ${Number(peekSeason().date.slice(8))} 日`:''}</span></div></header><main id="main" tabindex="-1">${body}</main></div><div id="toast" role="status" aria-live="polite"></div>`;
}
function currentPlayerView(p){
 const season=peekSeason();if(!season||p.retired||!p.club)return p;
 const current=seasonTeam(season,p.club).roster.find(x=>x.id===p.id);if(!current)return p;
 const keys={'传球':'passing','视野':'vision','控球':'firstTouch','速度':'pace','盘带':'dribbling','传中':'crossing','反应':'reflexes','扑救':'handling','出击':'rushingOut','防守':'tackling','预判':'anticipation','力量':'strength'};
 return {...p,age:current.age,skills:p.skills.map(([label,value])=>[label,keys[label]?Math.round(current.attributes[keys[label]]):value])};
}
function playerCard(p){p=currentPlayerView(p);const loc=location(p.city);const club=byId(clubs,p.club||p.lastClub);const d=drafts.find(d=>d.player===p.id);const family=byId(families,p.family);const academy=byId(academies,p.training[0]?.academy);return `<aside class="player-card"><div class="card-kicker"><span>球员档案</span><span>${String(players.indexOf(p)+1).padStart(3,'0')}</span></div><div class="portrait ${p.retired?'past':''}"><div class="portrait-rings"></div><div class="jersey"><span class="jersey-crest">✦</span><span class="jersey-team">${e(club?.short||'ASTRA')}</span><b>${p.number}</b><small>ASTRABALL</small></div><span class="portrait-label">${p.retired?'职业生涯档案':'球员身份卡'}</span><span class="vertical-label">${loc.region.en}</span></div><div class="card-main"><div class="card-eyebrow">${e(p.position)} <span>·</span> ${p.age} 岁 ${p.retired?badge('已退役'):''}</div><h2>${e(p.name)}</h2>${p.originalName&&p.originalName!==p.name?`<small class="name-original" dir="auto">${e(p.originalName)}</small>`:''}${club?route(entityPath(p,'club',club.id),`${e(club.name)} ${icon('arrow',14)}`,'club-link'):''}<p class="player-meta">${p.height?`${p.height} CM · ${p.foot} · `:''}${p.retired?'已退役 · 生涯代表期能力':'现役球员'}</p><div class="skills">${p.skills.map(([label,value])=>`<div><strong>${value}</strong><small>${label}</small></div>`).join('')}</div>${!p.retired&&p.club?`<a class="football-link" href="#squad/${p.club}/${p.id}">完整竞技属性 ↗</a>`:''}<div class="identity-links">${route(`player/${p.id}/place/province/${loc.province.id}`,`${icon('pin')}<span><small>出生地</small>${loc.province.name} · ${loc.city.name}</span>${icon('arrow',14)}`)}${academy?route(entityPath(p,'academy',academy.id),`${icon('school')}<span><small>培养经历</small>${academy.name}</span>${icon('arrow',14)}`):`<div class="identity-muted">培养经历尚未补录</div>`}${family?route(entityPath(p,'family',family.id),`${icon('family')}<span><small>家庭与谱系</small>${family.name}</span>${icon('arrow',14)}`):route(entityPath(p,'family','ordinary'),`${icon('family')}<span><small>家庭与谱系</small>普通家庭 · 亲属待补录</span>${icon('arrow',14)}`)}${d?route(entityPath(p,'draft',String(d.year)),`${icon('cup')}<span><small>职业起点</small>${d.year} 年 · 总第 ${d.overall} 顺位</span>${icon('arrow',14)}`):''}</div><button class="watch-button ${watched.has(p.id)?'is-watched':''}" data-watch="${p.id}">${icon('star',16)}${watched.has(p.id)?'取消关注':'关注球员'}</button></div></aside>`;}
function panelHead(title,description,tag=''){return `<div class="panel-head"><div><h2 tabindex="-1" id="panel-heading">${e(title)}</h2></div>${tag?badge(tag):''}</div>${description?`<p class="panel-description">${description}</p>`:''}`;}
function placePanel(p,kind,id){const list={city:cities,province:provinces,region:regions}[kind];const place=byId(list||provinces,id);if(!place)return empty('地区不存在');const loc=location(p.city);const root=kind==='region'?place:kind==='province'?byId(regions,place.region):location(place.id).region;const same=hometownPlayers(p,kind,id,mode);const records=hometownDrafts(kind,id);const suffix=kind==='city'?'城市':kind==='province'?'省份':'大区';return `<section class="explore-panel">${panelHead(place.name,'',`${suffix}档案`)}<div class="place-banner" style="--region-color:${root.color}"><div class="terrain-lines"></div><div><span>${root.en}</span><h3>${place.name}<small> / ${root.name}</small></h3><p>${root.terrain}</p></div>${icon('pin',38)}</div><div class="scope-bar"><span>探索范围</span>${[['city','城市'],['province','省份'],['region','大区']].map(([k,label])=>route(`player/${p.id}/place/${k}/${loc[k].id}`,label,kind===k&&id===loc[k].id?'active':'')).join('')}${route(`world/${root.id}`,'查看大区 ↗','region-link')}</div><div class="tabs" role="tablist" aria-label="地区人物分类"><button role="tab" aria-selected="${placeTab==='peers'}" data-tab="peers">同乡球员 <span>${same.length}</span></button><button role="tab" aria-selected="${placeTab==='drafts'}" data-tab="drafts">历届状元 <span>${records.length}</span></button></div>${placeTab==='peers'?`<div class="list-toolbar"><div><strong>现役同乡</strong><small>${p.retired?'已退役，无现役联赛':'同级别：各体系顶级联赛'}</small></div><label class="filter"><span class="sr-only">同乡筛选</span><select id="peer-mode"><option value="tier" ${mode==='tier'?'selected':''}>同级别</option><option value="league" ${mode==='league'?'selected':''}>同联赛</option><option value="all" ${mode==='all'?'selected':''}>全部现役</option></select></label></div><div class="player-list">${same.map(x=>row(x)).join('')||empty('无符合条件的球员')}</div>`:`<div class="list-toolbar"><div><strong>状元记录</strong><small>星冠联盟 · 288—317 年</small></div></div><div class="draft-list">${records.map((d,i)=>draftRow(d,`第 ${i+1} 位`)).join('')||empty('暂无状元记录')}</div>`}</section>`;}
function draftRow(d,tag=''){const p=byId(players,d.player);return route(playerPath(p.id),`<div class="draft-year">${d.year}</div><span class="avatar ${p.retired?'retired':''}">${e(p.name.slice(0,1))}</span><span class="row-name"><strong>${e(p.name)} ${p.retired?'<em>已退役</em>':''}</strong><small>${e(byId(clubs,d.club).name)} · 入选时 ${d.ageAtSelection} 岁</small></span><span class="row-detail">${e(tag||location(p.city).province.name)}</span>${icon('arrow',16)}`,'draft-row');}
function academyPanel(p,id){const a=byId(academies,id);if(!a)return empty('学院档案不存在。');const all=alumni(id);const training=p.training.find(t=>t.academy===id);const classmates=training?all.filter(x=>x.id!==p.id&&x.training.some(t=>t.academy===id&&t.to===training.to)):[];const winners=drafts.filter(d=>all.some(x=>x.id===d.player));return `<section class="explore-panel">${panelHead(a.name,e(a.text),a.kind)}<div class="institution-banner">${icon('school',56)}<div><span>成立于 ${a.founded} 年</span><p>${location(a.city).region.name} · ${location(a.city).city.name}</p></div></div><div class="mini-stats"><div><strong>${all.length}</strong><span>已收录校友</span></div><div><strong>${winners.length}</strong><span>历届状元</span></div><div><strong>${training?training.to:'—'}</strong><span>${training?'毕业年份':'无培养记录'}</span></div></div>${training?`<h3 class="section-title">${training.to} 届同学</h3>${classmates.map(x=>row(x)).join('')||empty('暂无其他同届学员记录')}`:''}<h3 class="section-title">知名校友</h3>${all.filter(x=>x.id!==p.id).slice(0,8).map(x=>row(x)).join('')||empty('暂无其他校友记录。')}</section>`;}
function familyPanel(p,id){const f=byId(families,id);const members=players.filter(x=>x.family===id);const kin=relatives(p.id);return `<section class="explore-panel">${panelHead(f?.name||'家庭档案',e(f?.text||'暂无家庭记录'),f?.type||'普通家庭')}<h3 class="section-title">${e(p.name)} 的亲属</h3>${kin.map(k=>row(k.player,k.label)).join('')||empty('暂无亲属记录')}${f?`<h3 class="section-title">家族人物</h3>${members.filter(x=>x.id!==p.id&&!kin.some(k=>k.player.id===x.id)).map(x=>row(x)).join('')||'<p class="muted">暂无其他成员记录</p>'}${f.parent?route(entityPath(p,'family',f.parent),`${icon('family')}主家族 · ${byId(families,f.parent).name} ${icon('arrow')}`,'entity-row'):''}${families.filter(x=>x.parent===f.id).map(x=>route(entityPath(p,'family',x.id),`${icon('family')}${x.name} ${icon('arrow')}`,'entity-row')).join('')}${route(`world/${location(f.origin).region.id}`,`${icon('pin')}家族发源地 · ${location(f.origin).city.name} ${icon('arrow')}`,'entity-row')}`:''}</section>`;}
function draftPanel(p,id){const d=drafts.find(x=>x.year===Number(id));if(!d)return empty('没有该年的选秀档案。');return `<section class="explore-panel">${panelHead(`${d.year} 年选秀`, '大都会星冠联盟','历史档案')}${draftRow(d,'总第 1 顺位')}<p class="archive-note">仅收录状元</p><h3 class="section-title">相邻年份</h3>${drafts.filter(x=>Math.abs(x.year-d.year)<=2&&x.year!==d.year).map(x=>route(entityPath(p,'draft',String(x.year)),`${x.year} 年选秀 <span>${e(byId(players,x.player).name)}</span>${icon('arrow')}`,'entity-row')).join('')}</section>`;}
function clubPanel(p,id){const c=byId(clubs,id);if(!c)return empty('俱乐部不存在。');const league=byId(leagues,c.league);const loc=location(c.city);const active=players.filter(x=>x.club===id);const former=players.filter(x=>x.lastClub===id);return `<section class="explore-panel">${panelHead(c.name,`${loc.region.name} · ${loc.city.name} · 成立于 ${c.founded} 年`,league.system)}<div class="club-banner"><b>${c.short}</b><span>${league.name}</span></div><p class="panel-description">${league.description}</p>${route(`leagues/${league.id}/1/rules`,'查看赛制 ↗','football-link')} ${route(`squad/${c.id}`,'完整阵容 ↗','football-link')}<h3 class="section-title">已收录现役球员 · ${active.length}</h3>${active.map(x=>row(x)).join('')||empty('现役名单尚未补录。')}<h3 class="section-title">退役球员</h3>${former.map(x=>row(x)).join('')||empty('退役名宿尚未补录。')}${route(`world/${loc.region.id}`,`${icon('globe')}查看 ${loc.region.name}${icon('arrow')}`,'entity-row')}</section>`;}
function playerView(s){const p=s.player;let panel=s.type==='academy'?academyPanel(p,s.entity):s.type==='family'?familyPanel(p,s.entity):s.type==='draft'?draftPanel(p,s.entity):s.type==='club'?clubPanel(p,s.entity):placePanel(p,s.kind,s.id);return `<div class="player-toolbar"><button class="back-button" data-back>${icon('back',16)}返回上一站</button></div><div class="player-layout">${playerCard(p)}<div class="right-column">${panel}<section class="story-panel"><div class="eyebrow">生涯记录</div><h3>${e(originStory(p))}</h3><div class="timeline">${p.career.length?p.career.map(c=>`<div class="timeline-item"><span>${c.year}</span>${route(entityPath(p,c.type,c.target),`${e(c.text)} ${icon('arrow',14)}`)}</div>`).join(''):`<p class="muted">${e(p.honors[0]?.text||'职业生涯详细记录尚未补录。')}</p>`}</div></section></div></div>`;}
function worldView(){return renderAtlas(window.location.hash);}
function render(focus=false){disposeManager();disposeAtlas();disposeFootball();disposeLeagues();disposeHub();const s=current();const section=['world','watch','player','match','squad','leagues','friendly','manager','coach'].includes(s.section)?s.section:'player';const body=section==='manager'?renderManager():section==='match'?renderHub():section==='leagues'?renderLeagues():['friendly','squad','coach'].includes(section)?renderFootball():section==='world'?worldView(s.worldId):section==='watch'?`<div class="page-heading"><div><h1>关注名单</h1><p>本地保存</p></div></div><section class="explore-panel watch-list">${players.filter(p=>watched.has(p.id)).map(p=>row(p)).join('')||empty('暂无关注球员')}</section>`:playerView(s);document.body.classList.toggle('atlas-active',section==='world');document.body.classList.toggle('football-active',['match','squad','leagues','friendly','manager','coach'].includes(section));app.innerHTML=shell(body,section,s.player);if(section==='manager')mountManager();if(section==='world')mountAtlas();if(section==='leagues')mountLeagues();if(section==='match')mountHub();if(['friendly','squad','coach'].includes(section))mountFootball();if(focus)document.querySelector('#main').focus({preventScroll:true});}
app.addEventListener('click',ev=>{const watch=ev.target.closest('[data-watch]');if(watch){const id=watch.dataset.watch;watched.has(id)?watched.delete(id):watched.add(id);let saved=true;try{localStorage.setItem('astraball-watch',JSON.stringify([...watched]));}catch{saved=false;}render();document.querySelector('[data-watch]')?.focus({preventScroll:true});const toast=document.querySelector('#toast');toast.textContent=saved?(watched.has(id)?'已加入关注名单':'已取消关注'):'浏览器存储不可用，关注仅在当前页面保留';setTimeout(()=>{toast.textContent='';},2500);return;}const tab=ev.target.closest('[data-tab]');if(tab){placeTab=tab.dataset.tab;render();document.querySelector(`[data-tab="${placeTab}"]`)?.focus({preventScroll:true});return;}if(ev.target.closest('[data-back]')){if(routeTrail.length){returning=true;window.location.hash=routeTrail.pop();}else{window.location.hash='world/sichuan';}return;}});
app.addEventListener('change',ev=>{if(ev.target.id==='peer-mode'){mode=ev.target.value;render();document.querySelector('#peer-mode')?.focus({preventScroll:true});}});
app.addEventListener('keydown',ev=>{if(!ev.target.closest('[data-tab]')||!['ArrowLeft','ArrowRight','Home','End'].includes(ev.key))return;ev.preventDefault();placeTab=ev.key==='Home'?'peers':ev.key==='End'?'drafts':placeTab==='peers'?'drafts':'peers';render();document.querySelector(`[data-tab="${placeTab}"]`)?.focus({preventScroll:true});});
window.addEventListener('hashchange',()=>{const previousPlayer=(lastRoute||playerPath('lin')).split('/')[1];viewStates.set(lastRoute||playerPath('lin'),{mode,placeTab});if(!returning)routeTrail.push(lastRoute||playerPath('lin'));returning=false;lastRoute=locationHash();const savedView=viewStates.get(lastRoute);mode=savedView?.mode||(current().player.retired?'all':'tier');placeTab=savedView?.placeTab||'peers';render(true);if(document.documentElement.clientWidth<=700&&current().section==='player'&&current().player.id===previousPlayer){document.querySelector('#panel-heading')?.scrollIntoView({block:'start'});}else{window.scrollTo({top:0,behavior:'instant'});}});
window.addEventListener('careerchange',()=>render());
mode=current().player.retired?'all':'tier';
render();

loadSeason().then(s=>{if(current().section==='player'){render();return;}const squad=document.querySelector('nav a[href^="#squad/"]');if(squad&&s.manager)squad.href=`#squad/${s.manager.clubId}`;const el=document.querySelector('.topbar .date');if(el)el.innerHTML=`<span>殖民历</span> ${s.year} <span>年 ${Number(s.date.slice(5,7))} 月 ${Number(s.date.slice(8))} 日</span>`;}).catch(()=>{});
