import {registeredPlayer} from '../competitions/registry.js';
import {developedPlayer} from '../competitions/development.js';
import {playerGrowthPanel} from './development-ui.js';
import {loadSeason,peekSeason,startOfficial,tickOfficial,saveOfficialPreparation,savePlayerTraining} from '../competitions/store.js';
import {seasonTeam} from '../competitions/runtime.js';
import {coachPreview} from '../competitions/career.js';
import {footballTeams} from './data.js';
import {ATTRIBUTE_GROUPS,POSITIONS,rating,selectLineup,available} from './players.js';
import {createMatch,stepMatch,applyCommand,DEFAULT_TACTICS,TACTIC_VALUES,restoreMatch} from './engine.js';
import {periodBase} from './rules.js';
import {cities,leagues} from '../world.js';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const team=id=>{if(official){const t=[official.input.home,official.input.away].find(t=>t.id===id);if(t)return t;}const t=footballTeams.find(t=>t.id===id)||footballTeams[0];return window.location.hash.startsWith('#squad')&&peekSeason()?seasonTeam(peekSeason(),t.id):t;};
const labels={formation:'阵型',passing:'传球',pressing:'逼抢',tempo:'节奏',line:'防线',width:'宽度',mentality:'倾向'};
const values={short:'短传',mixed:'混合',direct:'直传',low:'低位',balanced:'均衡',high:'高位',slow:'慢',normal:'标准',fast:'快',deep:'回收',narrow:'窄',wide:'宽',defensive:'防守',attacking:'进攻'};
const setup={home:'sky',away:'silver-fc',seed:318,knockout:false,tactics:[{...DEFAULT_TACTICS},{...DEFAULT_TACTICS}],lineups:[null,null]};
let state=null,timer=null,speed=6,cleanup=()=>{},root=null,generation=0,official=null,saving=false;
const clubOptions=id=>footballTeams.filter(t=>t.league===team(id).league).map(t=>[t.id,`${t.name} · ${leagues.find(l=>l.id===t.league).levels.find(d=>d.id===team(t.id).division).tier} 级`]);
const select=(name,options,value,attrs='')=>`<label>${esc(name)}<select ${attrs}>${options.map(([id,text])=>`<option value="${esc(id)}" ${String(id)===String(value)?'selected':''}>${esc(text)}</option>`).join('')}</select></label>`;
function profile(p){const city=cities.find(c=>c.id===p.city);return `<div class="football-profile"><header><div class="squad-monogram">${p.number||'—'}</div><div><small>${POSITIONS[p.position]} · ${p.age} 岁</small><h2>${esc(p.name)}</h2>${p.originalName&&p.originalName!==p.name?`<span class="name-original" dir="auto">${esc(p.originalName)}</span>`:''}<a href="#world/city/${esc(p.city)}">${esc(city?.name||'出生地')}</a></div><strong class="overall">${rating(p)}<small>当前能力</small></strong></header><div class="profile-facts"><span>身高 ${Math.round(p.height)} cm</span>${Number.isFinite(p.weight)?`<span>体重 ${p.weight.toFixed(1)} kg</span>`:''}<span>${p.foot==='left'?'左脚':'右脚'}</span><span>逆足 ${p.weakFoot}</span><span>体能 ${Math.round(p.condition)}</span><span>士气 ${p.morale}</span><span>比赛状态 ${p.sharpness}</span>${p.injuryDays?`<span>伤停 ${p.injuryDays} 天</span>`:''}${p.suspended?`<span>联赛停赛 ${p.suspended} 场</span>`:''}${p.playedToday?'<span>今日已出场</span>':''}</div>${p.worldId?`<a class="football-link" href="#player/${esc(p.worldId)}">人物与生涯 ↗</a>`:''}${peekSeason()&&location.hash.startsWith('#squad')?playerGrowthPanel(peekSeason(),p,{editable:true}):''}<div class="attribute-groups">${Object.entries(ATTRIBUTE_GROUPS).map(([key,g])=>`<section class="${key==='goalkeeper'&&p.position!=='GK'?'secondary-attributes':''}"><h3>${g.label}</h3>${Object.entries(g.fields).map(([id,label])=>`<div class="attribute-row"><span>${label}</span><i style="--value:${p.attributes[id]}%"></i><b class="${p.attributes[id]>=80?'strong':''}">${Math.round(p.attributes[id])}</b></div>`).join('')}</section>`).join('')}</div></div>`;}
function squadView(){const bits=window.location.hash.split('/'),t=team(bits[1]),season=peekSeason(),candidate=season&&bits[2]?registeredPlayer(season,bits[2]):null,requested=candidate&&candidate.club===t.id?developedPlayer(season,candidate):null,p=t.roster.find(p=>p.id===bits[2])||requested||t.roster[0];return `<div class="football-title"><div><small>一线队 · ${t.roster.length} 人</small><h1>球员与阵容</h1></div><a class="football-primary" href="#match">比赛中心 ↗</a></div><div class="squad-layout"><section class="squad-list"><a class="football-link" href="#youth">青训中心 ↗</a>${select('赛事',leagues.map(l=>[l.id,l.name]),t.league,'data-squad-system class="squad-system"')}${select('俱乐部',clubOptions(t.id),t.id,'data-squad-club')}<a class="football-link" href="#leagues/${t.league}/${leagues.find(l=>l.id===t.league).levels.find(d=>d.id===t.division).tier}/rules">联赛赛制 ↗</a><div class="squad-columns"><span>球员</span><span>位置</span><span>能力</span></div>${t.roster.map(q=>`<a href="#squad/${t.id}/${q.id}" class="squad-row ${p.id===q.id?'selected':''}"><span><b>${q.number}</b>${esc(q.name)}<small>${q.age} 岁</small></span><span>${q.position}</span><strong>${rating(q)}</strong></a>`).join('')}</section>${p?profile(p):'<p class="youth-empty">暂无球员</p>'}</div>`;}
function tactics(side){const settings=state?state.teams[side].tactics:setup.tactics[side];return `<div class="tactics-grid">${Object.entries(labels).map(([key,label])=>select(label,TACTIC_VALUES[key].map(v=>[v,values[v]||v]),settings[key],`data-tactic="${key}" data-side="${side}" ${state&&state.status!=='playing'?'disabled':''}`)).join('')}</div>`;}
function starters(side){const t=team(side?setup.away:setup.home),slots=setup.lineups[side]||selectLineup(t,setup.tactics[side].formation);setup.lineups[side]=slots;return `<div class="lineup-list">${slots.map((s,i)=>select(POSITIONS[s.position],t.roster.filter(available).map(p=>[p.id,`${p.name} · ${p.position} · ${rating(p,s.position)}`]),s.id,`data-slot="${i}" data-side="${side}"`)).join('')}</div>`;}
function matchView(){if(official)return officialView();return `<div class="football-title"><div><small>足球 · 友谊赛</small><h1>友谊赛</h1></div><a class="football-link" href="#squad/${setup.home}">查看球员 ↗</a></div><div class="match-setup">${select('主队赛事',leagues.map(l=>[l.id,l.name]),team(setup.home).league,`data-match-system="home" ${state?'disabled':''}`)}${select('客队赛事',leagues.map(l=>[l.id,l.name]),team(setup.away).league,`data-match-system="away" ${state?'disabled':''}`)}${select('主队',clubOptions(setup.home),setup.home,`data-team="home" ${state?'disabled':''}`)}<span class="versus">VS</span>${select('客队',clubOptions(setup.away),setup.away,`data-team="away" ${state?'disabled':''}`)}${select('赛制',[['league','常规赛'],['cup','淘汰赛']],setup.knockout?'cup':'league',`data-format ${state?'disabled':''}`)}<label>比赛种子<input aria-label="比赛种子" type="number" min="1" max="999999999" value="${setup.seed}" data-seed ${state?'disabled':''}></label></div><div class="match-actions"><button class="football-primary" data-action="${state?'toggle':'start'}" ${state&&state.status!=='playing'?'disabled':''}>${state&&state.status!=='playing'?'比赛结束':state?timer?'暂停':'继续比赛':'开始比赛'}</button><button data-action="finish" ${state?.status==='finished'?'disabled':''}>模拟至终场</button>${select('播放速度',[['1','慢速'],['6','标准'],['20','快速']],speed,'data-speed')}<button data-action="reset">重新布置</button><span id="match-notice" role="status"></span></div><div class="match-layout"><section class="match-stage" id="match-live"></section><aside class="match-coach"><h2>${esc(team(setup.home).name)}</h2>${tactics(0)}${state?substitutions(0):starters(0)}<details><summary>客队战术与阵容</summary>${tactics(1)}${state?substitutions(1):starters(1)}</details></aside></div><div id="match-player-detail"></div>`;}
function officialView(){
 const side=official.side,t=team(side?setup.away:setup.home),finished=state?.status==='finished';
 return `<div class="football-title"><div><small>${official.fixture.date} · 正式比赛 · ${side?'客场':'主场'}</small><h1>${esc(team(setup.home).name)} <span class="coach-vs">对</span> ${esc(team(setup.away).name)}</h1></div><a class="football-link" href="#manager">经理首页 ↗</a></div>
 <div class="match-actions"><button class="football-primary" data-action="${state?'toggle':'start'}" ${finished||saving?'disabled':''}>${finished?'比赛结束':state?timer?'暂停':'继续比赛':'开始正式比赛'}</button><button data-action="finish" ${finished||saving?'disabled':''}>委托至终场</button>${select('播放速度',[['1','慢速'],['6','标准'],['20','快速']],speed,'data-speed')}${finished?'<a class="football-primary" href="#manager">返回经理首页 →</a>':'<button class="coach-jump" data-action="coach">战术与换人 ↓</button>'}<span id="match-notice" role="status">${saving?'正在保存…':finished?'赛果已保存':state?'比赛进度已保存':'赛前布置'}</span></div>
 <div class="match-layout"><section class="match-stage" id="match-live"></section><aside class="match-coach"><h2>${esc(t.name)}</h2><button class="coach-jump" data-action="pitch">回到比赛 ↑</button><fieldset ${saving?'disabled':''}>${tactics(side)}${state?substitutions(side):starters(side)}</fieldset></aside></div><div id="match-player-detail"></div>`;
}
async function officialUpdate({steps=0,command}={}){
 if(saving)return;
 const token=generation,context=official;
 saving=true;
 try{
  const result=await tickOfficial({fixtureId:context.fixture.id,serial:context.serial,steps,command});
  if(token!==generation)return;
  state=result.state;context.serial=result.season.activeMatch?.serial;
  if(state.status!=='playing')stop();
 }catch(error){if(token===generation)stop();throw error;}
 finally{if(token===generation)saving=false;}
}
function substitutions(side){const t=state.teams[side],bench=t.roster.filter(p=>available(p)&&!t.used.has(p.id));return `<div class="match-subs"><h3>换人 <small>${t.subs} / 5 · ${t.windows} / 3 次</small></h3>${select('换下',t.slots.map(s=>[s.id,`${t.roster.find(p=>p.id===s.id).name} · ${Math.round(t.lines[s.id].condition)}%`]),t.slots.at(-1)?.id,`data-out="${side}"`)}${select('换上',bench.map(p=>[p.id,`${p.name} · ${p.position}`]),bench[0]?.id,`data-in="${side}"`)}<button data-action="sub" data-side="${side}" ${t.subs>=5||state.status!=='playing'?'disabled':''}>确认换人</button></div>`;}
function clockLabel(){if(!state)return '赛前';if(state.status==='abandoned')return '比赛中止';if(state.status==='finished')return state.shootout?'点球结束':'全场结束';const standard=state.period>2?15:45,m=state.periodClock/60;return m>standard?`${periodBase(state.period)+standard}+${Math.floor(m-standard)}′`:`${Math.floor(periodBase(state.period)+m)}′`;}
const slotCoordinates={GK:[6,34],LB:[25,8],RB:[25,60],CB:[22,27],DM:[39,34],CM:[46,25],AM:[65,34],LW:[74,10],RW:[74,58],ST:[83,34]};
function pitch(){const teams=state?.teams||[team(setup.home),team(setup.away)],event=state?.events.filter(e=>['pass','dribble','shot'].includes(e.type)).at(-1);return `<svg class="match-pitch" viewBox="0 0 1050 680" role="img" aria-label="比赛场地与球的位置"><defs><pattern id="pitch-stripe" width="150" height="680" patternUnits="userSpaceOnUse"><rect width="75" height="680" fill="#ffffff04"/></pattern></defs><rect width="1050" height="680" fill="#203f34"/><rect width="1050" height="680" fill="url(#pitch-stripe)"/><g fill="none" stroke="#aec0a3" stroke-opacity=".4" stroke-width="2"><rect x="30" y="30" width="990" height="620"/><path d="M525 30V650M30 140H195V540H30M1020 140H855V540H1020M30 250H85V430H30M1020 250H965V430H1020"/><circle cx="525" cy="340" r="91.5"/></g>${teams.map((t,side)=>{const counts={};const slots=state?t.slots:setup.lineups[side];return slots.map(slot=>{const p=t.roster.find(p=>p.id===slot.id),base=slotCoordinates[slot.position];let [x,y]=base;const n=counts[slot.position]||0;counts[slot.position]=n+1;if(slot.position==='CB')y=24+n*14;else if(n)y+=16;const active=event?.player===p.id;if(active&&event){x=side?105-event.x:event.x;y=side?68-event.y:event.y;}if(side){x=105-x;y=68-y;}return `<g transform="translate(${x*10},${y*10})"><title>${esc(p.name)} · ${POSITIONS[slot.position]}</title><circle r="${active?21:17}" fill="${side?'#cec7ae':'#d4ac62'}" stroke="#172b26" stroke-width="3"/><text text-anchor="middle" y="5" font-size="17" fill="#172b26">${p.number||''}</text>${active?`<text text-anchor="middle" y="40" font-size="20" fill="#edf0da" stroke="#1b352b" stroke-width="3" paint-order="stroke">${esc(p.name)}</text>`:''}</g>`;}).join('');}).join('')}${event?`<circle cx="${(event.to?.[0]??event.x)*10}" cy="${(event.to?.[1]??event.y)*10}" r="7" fill="#fff" stroke="#111" stroke-width="2"/>`:''}</svg>`;}
function describe(e){const p=state.teams.flatMap(t=>t.roster).find(p=>p.id===e.player),name=p?.name||'';return e.type==='shot'?`${name} · ${{goal:'进球',save:'被扑出',miss:'射偏',blocked:'被封堵'}[e.outcome]}${e.kind==='penalty'?'（点球）':''}`:e.type==='substitution'?`${name} ↓ ${state.teams.flatMap(t=>t.roster).find(p=>p.id===e.incoming)?.name} ↑`:e.type==='yellow'?`${name} · 黄牌`:e.type==='red'?`${name} · ${e.secondYellow?'两黄变红':'红牌'}`:e.type==='injury'?`${name} · 伤退`:e.type==='corner'?`${name} · 角球`:e.type==='offside'?`${name} · 越位`:e.type==='shootout'?`${name} · 点球${e.goal?'命中':'未进'}`:e.type==='periodEnd'?'本节结束':e.type==='periodStart'?'开球':e.type==='fullTime'?'全场结束':e.type==='abandoned'?'场上不足七人，比赛中止':e.type==='tactics'?'战术调整':'';}
function live(){const target=root?.querySelector('#match-live');if(!target)return;const score=state?.teams.map(t=>t.stats.goals)||[0,0];const highlights=state?.events.filter(e=>describe(e)).slice(-16).reverse()||[];target.innerHTML=`<div class="scoreboard"><span>${esc(team(setup.home).short)}</span><strong>${score[0]} <i>:</i> ${score[1]}</strong><span>${esc(team(setup.away).short)}</span><small>${clockLabel()}${state?.shootout?` · 点球 ${state.shootout.score.join(' : ')}`:''}</small></div>${pitch()}<div class="match-statistics">${[['shots','射门'],['onTarget','射正'],['xG','预期进球'],['passes','传球'],['completed','成功传球'],['corners','角球'],['fouls','犯规'],['yellow','黄牌'],['red','红牌']].map(([key,label])=>`<div><b>${state?(key==='xG'?state.teams[0].stats[key].toFixed(2):state.teams[0].stats[key]):'—'}</b><span>${label}</span><b>${state?(key==='xG'?state.teams[1].stats[key].toFixed(2):state.teams[1].stats[key]):'—'}</b></div>`).join('')}</div><div class="match-log"><h3>比赛记录</h3>${highlights.map(e=>`<div class="${e.type==='shot'&&e.outcome==='goal'?'goal-event':''}"><time>${Math.floor(e.minute)}′</time><span>${esc(describe(e))}</span></div>`).join('')||'<p>等待开球</p>'}</div>${state?`<div class="match-boxscore"><h3>球员表现</h3><table><thead><tr><th>球员</th><th>分钟</th><th>进球</th><th>助攻</th><th>射门</th><th>xG</th><th>体能</th></tr></thead><tbody>${state.teams.map(t=>`<tr class="team-row"><th colspan="7">${esc(t.name)}</th></tr>${Object.values(t.lines).filter(l=>l.seconds>0).map(l=>`<tr><td><button data-player="${l.id}">${esc(t.roster.find(p=>p.id===l.id).name)}</button></td><td>${Math.round(l.seconds/60)}</td><td>${l.goals}</td><td>${l.assists}</td><td>${l.shots}</td><td>${l.xG.toFixed(2)}</td><td>${Math.round(l.condition)}%</td></tr>`).join('')}`).join('')}</tbody></table></div>`:''}`;}
function stop(){if(timer)clearInterval(timer);timer=null;}
function redraw(){if(!root)return;root.innerHTML=window.location.hash.startsWith('#squad')?squadView():matchView();live();}
function start(){const seed=Number(root.querySelector('[data-seed]').value);if(!Number.isInteger(seed)||seed<1||seed>999999999)throw Error('种子须为 1—999999999 的整数');setup.seed=seed;if(setup.home===setup.away)throw Error('请选择两支不同的球队');state=createMatch({home:team(setup.home),away:team(setup.away),seed:setup.seed,knockout:setup.knockout,homeTactics:setup.tactics[0],awayTactics:setup.tactics[1],homeLineup:setup.lineups[0],awayLineup:setup.lineups[1]});}
function play(){stop();if(state?.status!=='playing')return;if(official){const token=generation;timer=setInterval(async()=>{if(saving)return;try{await officialUpdate({steps:speed*4});if(token===generation){if(state.status==='playing')live();else redraw();}}catch(error){if(token===generation&&root){redraw();root.querySelector('#match-notice').textContent=error.message;}}},400);redraw();return;}timer=setInterval(()=>{for(let i=0;i<speed&&state.status==='playing';i++)stepMatch(state);live();if(state.status!=='playing'){stop();redraw();}},160);redraw();}
export function renderFootball(){return '<section id="football-root" class="football-page"></section>';}
export function disposeFootball(){generation++;stop();cleanup();root=null;}
export async function mountFootball(){root=document.querySelector('#football-root');if(!root)return;const token=++generation;if(location.hash.startsWith('#coach')){
  try{
   const season=await loadSeason();if(token!==generation)return;
   official=coachPreview(season);official.serial=season.activeMatch?.serial;
   setup.home=official.input.home.id;setup.away=official.input.away.id;
   setup.tactics=[{...DEFAULT_TACTICS},{...DEFAULT_TACTICS}];setup.tactics[official.side]=official.tactics;
   setup.lineups=[selectLineup(official.input.home),selectLineup(official.input.away)];setup.lineups[official.side]=official.lineup;
   state=season.activeMatch?restoreMatch(season.activeMatch.state):null;
  }catch(error){if(token===generation)root.innerHTML=`<h1>执教比赛</h1><p role="alert">${esc(error.message)}</p><a class="football-primary" href="#manager">返回经理首页</a>`;return;}
 }else{
  if(official){state=null;setup.home='sky';setup.away='silver-fc';setup.tactics=[{...DEFAULT_TACTICS},{...DEFAULT_TACTICS}];setup.lineups=[null,null];}
  official=null;
  if(location.hash.startsWith('#squad')){try{await loadSeason();}catch{}}
 }
 if(token!==generation)return;saving=false;redraw();
 const click=async ev=>{const b=ev.target.closest('[data-action],[data-player]');if(!b||saving)return;try{
  if(official&&['start','toggle','finish','sub'].includes(b.dataset.action)){
   const action=b.dataset.action;
   if(action==='toggle'){if(timer){stop();redraw();}else play();return;}
   stop();
   if(!state){saving=true;redraw();const result=await startOfficial({fixtureId:official.fixture.id,tactics:setup.tactics[official.side],lineup:setup.lineups[official.side]});if(token!==generation)return;state=result.state;official.serial=result.season.activeMatch.serial;saving=false;}
   if(action==='start'){play();return;}
   if(action==='finish')await officialUpdate({steps:20000});
   if(action==='sub'){const side=official.side;await officialUpdate({command:{type:'substitution',side,out:root.querySelector(`[data-out="${side}"]`).value,in:root.querySelector(`[data-in="${side}"]`).value}});}
   if(token===generation)redraw();return;
  }
  if(b.dataset.player){stop();const p=state.teams.flatMap(t=>t.roster).find(p=>p.id===b.dataset.player);redraw();root.querySelector('#match-player-detail').innerHTML=`<button data-action="close-profile">收起档案</button>${profile({...p,condition:state.teams.find(t=>t.lines[p.id]).lines[p.id].condition})}`;root.querySelector('#match-player-detail').scrollIntoView({block:'start'});return;}
  switch(b.dataset.action){case 'coach':root.querySelector('.match-coach').scrollIntoView({block:'start'});break;case 'pitch':root.querySelector('.match-actions').scrollIntoView({block:'start'});break;case 'start':start();play();break;case 'toggle':if(timer){stop();redraw();}else play();break;case 'finish':stop();if(!state)start();while(state.status==='playing')stepMatch(state);redraw();break;case 'reset':stop();state=null;redraw();break;case 'sub':{stop();const side=Number(b.dataset.side);applyCommand(state,{type:'substitution',side,out:root.querySelector(`[data-out="${side}"]`).value,in:root.querySelector(`[data-in="${side}"]`).value});redraw();break;}case 'close-profile':root.querySelector('#match-player-detail').innerHTML='';break;}
 }catch(error){if(token!==generation)return;saving=false;stop();if(official)redraw();const notice=root.querySelector('#match-notice');if(notice)notice.textContent=error.message;}};
 const change=async ev=>{const el=ev.target;if(saving)return;
  if(el.dataset.growth){
   const notice=root.querySelector('#growth-notice'),focus=root.querySelector('[data-growth="focus"]').value,load=Number(root.querySelector('[data-growth="load"]').value);
   saving=true;for(const field of root.querySelectorAll('[data-growth]'))field.disabled=true;notice.textContent='正在保存…';
   try{await savePlayerTraining(el.dataset.growthPlayer,{focus,load});if(token===generation){saving=false;redraw();root.querySelector('#growth-notice').textContent='已保存';}}
   catch(error){if(token===generation){saving=false;redraw();root.querySelector('#growth-notice').textContent=error.message;}}return;
  }
  try{
  if(el.hasAttribute('data-out')||el.hasAttribute('data-in'))return;
  if(el.hasAttribute('data-squad-system')){window.location.hash=`squad/${footballTeams.find(t=>t.league===el.value).id}`;return;}
  if(el.hasAttribute('data-match-system')){const side=el.dataset.matchSystem;setup[side]=footballTeams.find(t=>t.league===el.value).id;setup.lineups[side==='home'?0:1]=null;redraw();return;}
  if(el.hasAttribute('data-squad-club')){window.location.hash=`squad/${el.value}`;return;}
  if(el.dataset.team){setup[el.dataset.team]=el.value;setup.lineups[el.dataset.team==='home'?0:1]=null;}
  if(el.hasAttribute('data-format'))setup.knockout=el.value==='cup';
  if(el.hasAttribute('data-seed')){const seed=Number(el.value);if(!Number.isInteger(seed)||seed<1||seed>999999999)throw Error('种子须为 1—999999999 的整数');setup.seed=seed;return;}
  if(el.hasAttribute('data-speed'))speed=Number(el.value);
  if(el.dataset.tactic){const side=Number(el.dataset.side);if(state){stop();const command={type:'tactics',side,tactics:{[el.dataset.tactic]:el.value}};if(official){await officialUpdate({command});if(token!==generation)return;}else applyCommand(state,command);}else{setup.tactics[side][el.dataset.tactic]=el.value;if(el.dataset.tactic==='formation')setup.lineups[side]=null;}}
  if(el.hasAttribute('data-slot')){const side=Number(el.dataset.side),i=Number(el.dataset.slot),slots=setup.lineups[side],other=slots.findIndex(s=>s.id===el.value),old=slots[i].id;slots[i].id=el.value;if(other>=0&&other!==i)slots[other].id=old;}
  if(official&&!state&&(el.dataset.tactic||el.hasAttribute('data-slot'))){saving=true;redraw();await saveOfficialPreparation({fixtureId:official.fixture.id,tactics:setup.tactics[official.side],lineup:setup.lineups[official.side]});if(token!==generation)return;saving=false;}
  redraw();
 }catch(error){if(token===generation&&root){saving=false;redraw();root.querySelector('#match-notice').textContent=error.message;}}};
 root.addEventListener('click',click);root.addEventListener('change',change);const mounted=root;cleanup=()=>{mounted.removeEventListener('click',click);mounted.removeEventListener('change',change);};
}
